### ISSUE TITLE
Value cannot be null. Parameter name: Input

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.NET#125]
I have just picked my existing xamarin.forms tizen project after some time and tried to debug on my GW Classic 4 and i am getting straight away this error message. There is no additional information although i have turned on Diagnostic builds. 
I have created a new app from the default template to see if it is my project specific, it is exactly same error with the default template without changing anything. 
Can you please help here?

**Comment by sangwook96** [comment]
Hi, @EmilAlipiev 
Sorry for the bad experience, Can you please provide the below detail to investigate this issue further.
1. Is tizen studio path set in Tools -> option -> tizen -> tool
2. Installed tizen studio version
3. List of platform and profiles installed in tizen studio

In detail, 
We can debug 6.5/5.5 wearable  xamarin forms apps on the ide, now.
Just please follow the below guide step by step.
https://docs.tizen.org/application/vstools/install/#visual-studio-tools-for-tizen-installation
https://docs.tizen.org/application/vstools/install/#installing-the-tizen-baseline-sdk
https://docs.tizen.org/application/vstools/install/#setting-the-tizen-baseline-sdk-path
https://docs.tizen.org/application/vstools/install/#installing-emulator-images => Install 6.5 or 5.5 wearable profile

Thanks

**Comment by EmilAlipiev** [comment]
Tizen studio version: 4.1 but i am not sure what is "List of platform and profiles installed in tizen studio"? My VS and Tizen Studio are always the same and works fine on Active watch 2. I have problem with Classic watch 4. 
When I connect using VS, VS2019 is showing as available device but when I try to debug, i get this popup as error message. One thing also different than Active 2 is that Tizen Device Manager shows connected via Wifi but i dont see any logs in the device manager window. this is shown for Active 2?

**Comment by EmilAlipiev** [comment]
This is how it looks like. 

<img width="292" alt="image" src="https://user-images.githubusercontent.com/10422347/145920790-26b895bd-bb11-44a9-8bcd-b26fecd54396.png">

**Comment by EmilAlipiev** [comment]
I am not sure it is even actually Tizen is working with VS2019 any longer?

see the image below. Connection is successful but logs panel doesnt display anything. it used to display logs from the watch before. 

<img width="752" alt="image" src="https://user-images.githubusercontent.com/10422347/147390411-74eb53d5-0e26-4523-b607-cbb605ddd451.png">

VS2019 shows the connection is successful but when i press the debug button i get above "value cannot be null" error.
I have tried with my watch1 version, result is same. The same problem with a fresh new project.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/10422347/147390437-d1c83a46-26ae-45f6-b833-a1e7c88be4fc.png">

**Comment by dkson95** [comment]
@EmilAlipiev Would you make sure that the issue is reproducible even on latest release ?

https://marketplace.visualstudio.com/items?itemName=tizen.VSToolsforTizen

As the issue is not reproducible target/ emulator on here, would you check another device or wearable emulators in case the device might be corrupted ?

Thank you!

**Comment by EmilAlipiev** [comment]
@dkson95 @sangwook96 

  If i have misunderstanding here maybe, please correct me. I was originally talking about Galaxy watch 4 which has wear Os powered by Samsung as OS. I thought that I can still debug/run tizen apps on GW4. Is that not the case?
  On the seller center of Samsung, when i want to publish my tpk, there is option select watch types and GW4 is in the list as well.
