### ISSUE TITLE
Checking `Tizen .NET API Level` with `api-version` in `tizen-manifest.xml`

### ISSUE THREAD

**Issue by WonyoungChoi** [Samsung/Tizen.NET#138]
The `api-version` attribute of the `manifest` element represents the Tizen platform version. For example, if the `api-version` is `4`, the tpk can be installed only in version 4.0 or higher. 
```xml
<manifest xmlns="http://tizen.org/ns/packages" api-version="4" package="com.companyname.test1" version="1.0.0">
```
However, `tizen-manifest.xml` does not describe the Tizen .NET API Level. Therefore, it is necessary to check whether the available API Level has been used using the `api-version` during the TPK packaging process.

### Mapping between API Level and api-version
| API Level | api-version |
|-----------|-------------|
| 4 | 4.0 |
| 5 | 5.0 |
| 6 | 5.0 |
| 7 | 5.5 |
| 8 | 6.0 |
| 9 | 6.5 |
| 10 | 7.0 |

### Scenario
1. `tizen60` TFM is used in .csproj, and `api-version` is `4`
If `Tizen` target framework is used, we can know the `API Level` from `TargetFrameworkVersion` property.
In the case of the `tizen60` TFM, the `API Level` is 6, so the mapped `api-version` is 5.0. 
If the `api-version` is 4 described in the `tizen-manifest.xml`, the TPK packaging should fail because the mapped version is higher.

2. `net6.0-tizen7.0` TFM is used in .csproj `api-version` is `7`
If `.NET6` target framework is used, we can know the `api-version` from `TargetPlatformVersion` property. 
In this case, the `api-version` of `tizen-manifest.xml` and the `TargetPlatformVersion` value may be directly compared.

**Comment by JoonghyunCho** [comment]
Just to remember, MAUI Tizen Template needs to be updated after applying this change. :)

**Comment by r-dadhich** [comment]
Hello Mr. Choi,

Tizen.NET api version is also present under application type tag.
for example: 
<ui-application appid="org.tizen.example.ElmSharpTemplate4"
                    exec="ElmSharpTemplate4.dll"
                    type="dotnet"
                    multiple="false"
                    taskmanage="true"
                    nodisplay="false"
                    launch_mode="single"
                    **api-version**="9">

Please share your thoughts.

Regards,

**Comment by WonyoungChoi** [comment]
@r-dadhich Yes, but the `api-version` attribute of `*-application` element was not actually being used as we intended in APPFW. 
So we agree with VD and APPFW to delete the attribute of `*-application` element.

**Comment by EmilAlipiev** [comment]
Thats a good issue. I was just about to create a new issue I was getting related to this. Probably I can ask directly here. 
When I set my app targetin 6.5 and my target Watch has 5.5 installed. I am getting the error message below

<img width="286" alt="image" src="https://user-images.githubusercontent.com/10422347/153329084-692cc845-d86d-4c6b-8225-90d925821974.png">

I am not exactly sure how to solve this. Because I have everything related to 6.5 installed through Package manager. 
I thought that VS2022 should be used for targeting tizen 6.5 as stated [here](https://docs.tizen.org/application/vstools/install/) But this didnt help as well. I get same error. When I downgrade to 5.5, everything works fine.

**Comment by EmilAlipiev** [comment]
One last question to clarify what you wrote, so the  `api-version` is basically `minimum version`, not the target version or compile version like on android? I dont have any benefits if i set it 6 or 6.5? This is bit confusing though

**Comment by WonyoungChoi** [comment]
@EmilAlipiev The meaning of `api-version` of `tizen-manifest.xml` is the minimum Tizen platform version in which the app can be installed. Please check the `tizen-manifest.xml` first.  The VS error message occurs when the `platform_version` value of `sdb capability` result is lower than `api-version` value of `tizen-manifest.xml` file. Compiling version is determined by the `TargetFramework` of `.csproj`. If `TargetFramework` is `tizen40`, your app will be built with Tizen .NET API Level 4 provided from Tizen Platform 4.0. If `TargetFramework` is `tizen90`, it will be built with Tizen .NET API Level 9 provided from Tizen Platform 6.5.
