### ISSUE TITLE
An default Blazor template application has a crash occurred.

### ISSUE THREAD

**Issue by sung-su** [Samsung/Tizen.NET#139]
An default Blazor template application has a crash occurred with below error.
```
E/STDERR  ( 6353): Unhandled exception. System.TypeLoadException: GenericArguments[1], 'System.Object', on 'Microsoft.Maui.Handlers.ViewHandler`2[TVirtualView,TNativeView]' violates the constraint of type parameter 'TNativeView'.
```

This problem occurs when `workload` reference and does not occur when project referenced.
The `TargetFramework` is `net6.0-tizen`, but refers to `net6.0` of the `Microsoft.AspNetCore.Components.WebView.Maui` package.

Steps to reproduce:
1. MAUI Tizen workload & template installed environment.
2. Create a default .NET MAUI Blazor App template on Visual Studio.
3. Build by workload with net6.0-tizen target framework 
4. Run the app on Tizen emulator.
4. Exception occurs on app launching step.

template
[Microsoft.Maui.Templates.6.0.200-dev.nupkg.zip](https://github.com/Samsung/Tizen.NET/files/7999861/Microsoft.Maui.Templates.6.0.200-dev.nupkg.zip)

nuget
fixed nuget ( removed net6.0 )
[Microsoft.AspNetCore.Components.WebView.Maui.6.0.101-preview.11.2349.nupkg.zip](https://github.com/Samsung/Tizen.NET/files/7999916/Microsoft.AspNetCore.Components.WebView.Maui.6.0.101-preview.11.2349.nupkg.zip)
problem nuget (with net6.0 )
[Microsoft.AspNetCore.Components.WebView.Maui.6.0.200-dev.nupkg.zip](https://github.com/Samsung/Tizen.NET/files/7999918/Microsoft.AspNetCore.Components.WebView.Maui.6.0.200-dev.nupkg.zip)
![nuget](https://user-images.githubusercontent.com/10704816/152469481-7ca8e61d-e72f-4d2f-9234-46633bc9a581.png)

**Comment by WonyoungChoi** [comment]
@sung-su Could you add `repro steps` in the description?

**Comment by JoonghyunCho** [comment]
@WonyoungChoi Here's the steps to reproduce. @sung-su Please fix me if I'm wrong.

Environment: MAUI Tizen workload installed environment.
Steps to reproduce:
- Create a default `.NET MAUI Blazor App` template on Visual Studio.
- Build and Run the app on Tizen device.
- Exception occurs on app launching step.

**Comment by sung-su** [comment]
@JoonghyunCho Thank you.
@WonyoungChoi  Description updated.

**Comment by WonyoungChoi** [comment]
@sung-su @JoonghyunCho 
Please see https://github.com/xamarin/xamarin-android/pull/6026

**Comment by JoonghyunCho** [comment]
Thanks a lot for finding out the solution. I think we can also do the same for Tizen.
I will make a PR soon!
