### ISSUE TITLE
Having issues in installing Tizen workload from within Visual Studio 2022 when both .NET 7 and .NET 6 Preview are installed on the same machine

### ISSUE THREAD

**Issue by egvijayanand** [Samsung/Tizen.NET#159]
Having issues in installing Tizen workload from within Visual Studio 2022 when both .NET 7 and .NET 6 Preview are installed on the same machine.

Whereas switching to CLI mode (PowerShell) with a global.json file pointing to .NET 6 SDK allows installing the workload without any issues.

The VS extension should also detect the presence of .NET 6 and proceed with the installation from within IDE itself.

**Comment by sung-su** [comment]
@Egvijayanand
It seems that you need to run VS with admin rights to install the Tizen workload.
Please check below page.
https://github.com/Samsung/Tizen.NET/wiki/Trouble-Shooting
After this, if you still have a problem, please share more detailed information for reproduction.

**Comment by egvijayanand** [comment]
Hi @sung-su,

Since I've already installed the Tizen workload via PowerShell CLI from a folder context with the below global.json command pointing to .NET 6.

```shell
dotnet new globaljson --sdk-version 6.0.200 --roll-forward latestMinor
```

So am unable to verify the resolution provided in the above link.

Regards,
Vijay Anand E G

**Comment by sung-su** [comment]
@egvijayanand 
I understood now.
As you say, it seems that consideration of the `.NET 7` is needed.
We will refer your good opinion to the next development.
