### ISSUE TITLE
[OptionsPage] Impossible to see whole Tizen/Tools page with enlarged Environment font

### ISSUE THREAD

**Issue by xperiandri** [Samsung/Tizen.NET#164]
Having enlarged Environment font (DPI scale 250%)

![image](https://user-images.githubusercontent.com/2365592/168472834-2106aa06-ea1d-439f-8890-69853f84c99f.png)

because of constrained options control size the bottom of `Tizen\Tools` page is not visible

![image](https://user-images.githubusercontent.com/2365592/168472791-665c3e1f-ea83-4503-8ae1-48c5db79742a.png)

Fix the page layout, please

**Comment by JoonghyunCho** [comment]
@sangwook96-lee Please take a look on this situation and give some feedback. Thanks!

**Comment by sangwook96** [comment]
Hi, @xperiandri , @JoonghyunCho
Sorry for missing it and I will check it soon.

**Comment by xperiandri** [comment]
It would be nice if you fix that using `TableLayout` panel to make layout work in all circumstances

**Comment by JoonghyunCho** [comment]
@sangwook96 any updates on this?

**Comment by sangwook96** [comment]
Hi.
Okay, we will check it and we will inform it again

**Comment by JoonghyunCho** [comment]
@sangwook96 Any updates on this?

**Comment by xperiandri** [comment]
Ping

**Comment by sangwook96** [comment]
@xperiandri 
Ah, sorry, I have not checked it yet.
Let me update it soon

**Comment by xperiandri** [comment]
is it fixed?
