### ISSUE TITLE
[Uno Platform] support

### ISSUE THREAD

**Issue by xperiandri** [Samsung/Tizen.NET#167]
[Uno Platform](https://github.com/unoplatform/uno/) already had the support of Tizen 5 on .NET 5.
It would be nice if you put some effort into bringing Tizen on .NET 6 within a single .NET 6 Uno Platform project to make it happen faster.

**Comment by MartinZikmund** [comment]
Just to add to this - we had support, but some things were not stabilized too well yet - for example input. We would love to have first-class Tizen support however 🙂 .

**Comment by JoonghyunCho** [comment]
@xperiandri Thanks for your opinion and interest on Tizen!
@MartinZikmund Thanks for your hospitality :)
Now we are focusing all our effort to get Tizen released successfully to the world with MAUI. We will then have several more big changes in the internal Tizen backends.
Hopefully, at that moment, Tizen have more room to do something more.
