### ISSUE TITLE
are appium support TV Platform 

### ISSUE THREAD

**Issue by gopi-chand** [Samsung/Tizen.NET#177]
we are looking for Samsung TV device UI automation so are current appium framework  support for TV platform. if not when can we expect the support?. Thanks

**Comment by shyunMin** [comment]
Unfortunately, Appium is not yet supported on Samsung TV due to security policies.

https://developer.samsung.com/tizen/Smart-TV/FAQ/Smart-TV/Known-issue-2018.html
