### ISSUE TITLE
How to install Tizen.NET SDK in a CI environment that doesn't have VS2022 installed in it

### ISSUE THREAD

**Issue by egvijayanand** [Samsung/Tizen.NET#181]
Trying to do some automation on the build process (through GitHub Actions) for a .NET MAUI library. But could not able to find an automated procedure to install the Tizen.NET SDK in a CI environment that doesn't have VS2022 installed in it.

Kindly provide the steps to achieve the same.

**Comment by egvijayanand** [comment]
Expecting a command like below (similar to that of MAUI).

If necessary, additional package source(s) can be passed as input via `--source` parameter.

```shell
dotnet workload install tizen
```

**Comment by rookiejava** [comment]
Refer to below `build.yml` file.

https://github.com/Samsung/Tizen.TV.UIControls/blob/f2e356ff96b97ad685284292885c49179d1bf5e8/.github/workflows/build.yml#L1-L34

**Comment by egvijayanand** [comment]
Thanks for the details @rookiejava 

Will check and update.
