### ISSUE TITLE
Not possible to (un)install Tizen VSIX due to debugger

### ISSUE THREAD

**Issue by veikkoeeva** [Samsung/Tizen.NET#185]
I uninstalled Tizen extension in Visual Studio 2022 (VS) and then tried to re-install it. First time opening VS the Visual Studio Tools for Tizen was not present. I closed VS and re-opened it and found the extension was on disabled state. Upon trying to re-enable it I received the following message

![kuva](https://user-images.githubusercontent.com/5158694/176429982-69480c30-4c3e-4856-a402-ad9c7373a5e6.png)

So "Tizen MI-based Debugger" seem to be in disabled state. How to enable it or maybe remove it with extensions and then trying to install the extension again?

The instruction I used were from https://github.com/Samsung/Tizen.NET/wiki/Installing-Tizen-.NET-Workload (continuing from https://github.com/dotnet/maui/issues/8035#issuecomment-1166618505).

While thinking how to solve this installation problem, I tried to install the tooling on other machine according to the instructions. It might be useful to note that the step
> 3. Select **Install Tizen Workload (Preview).**

at https://github.com/Samsung/Tizen.NET/wiki/Installing-Tizen-.NET-Workload requires running VS in Admin mode and also to make a note to check the Output console print (should I make a PR?).

After doing that the various tool paths still remain empty and if I create a new Maui project it's not possible to start or debug a Tizen project (I did add `net6.0-tizen` to `TargetFrameworks` in `.csproj` to the same effect as uncommenting the commented line, maybe ought to be in instructions also).

Trying to install the workload using the script `workload-install.ps1` results in
> An exception was caught: The remote server returned an error: (404) Not Found.

**Comment by JoonghyunCho** [comment]
@sangwook96-lee Please take a look.

**Comment by JoonghyunCho** [comment]
@veikkoeeva If the Tizen workload install proceeds and it's done with the install success log at the end like "Done installing Tizen workload..." , the workload is good to go with 404 error. You can try `dotnet workload list` in the command line to make sure if `tizen` is installed.

**Comment by sangwook96** [comment]
@veikkoeeva,
Hi
Thanks, and could you follow the below steps?
1. Download the vsix from https://marketplace.visualstudio.com/items?itemName=tizen.VSToolsTizen2022
2. Unzip it to temp folder
3. cd temp
4. See the Tizen.MIDebugPackage.vsix
5. Install Tizen.MIDebugPackage.vsix manually
6. Closed VS and re-opened it and found the extension was on disabled state. **Upon trying to re-enable it**


Thanks

**Comment by JoonghyunCho** [comment]
@veikkoeeva Debug Maui Tizen application now has an issue on Visual Studio Preview 2022. SDK team is working on to enable it. Sorry for the inconvenience.

**Comment by veikkoeeva** [comment]
@sangwook96 I was able to move forwards with your explicit instruction to manually install the debugging extension. But not quit there. Now when I try to debug the solution in Tizen, I receive

> EP1700: The recipe file "\MauiWebView\MauiWebView\bin\Debug\net6.0-tizen\tizen-x86\MauiWebView.build.appxrecipe" does not exist. You may need to build your project.
2>Deployment of the application to the target device failed.

Indeed, the file does not exist. Should it be created in the build step?

Here `MauiWebView` is the name of the application, created using the VS 2022 template.

Also, in case someone someone else is looking a solution to this problem, I did a few extra steps to get this working.

- Upon install the extension manually I had to open VS 2022 but could not enable the main extension that was disabled.
- I closed VS 2022 on opened it again whereupon  I was able to enable the extension.
- I then needed to close VS 2022 again and open it. I received an error similar in the linked post that `tizen-6.0` wouldn't be recognized. 
- I closed VS 2022 and opened it in Admin mode and went to `Tools` -> `Options...` -> `Tizen` and enabled the workload again (even if looked like being enabled)
![kuva](https://user-images.githubusercontent.com/5158694/176765345-92e046f0-b88a-4a59-84da-7bad188d3453.png)
- I restarted Visual Studio and compiing worked. But now I get that aforementioned error.

**Comment by JoonghyunCho** [comment]
@veikkoeeva Debugging Maui (net6.0-tizen) app now has an issue on Visual Studio 2022 and I was told the recipe issue will be fixed on the next VS release. I expect those whole debugging issue would be fix probably after this Oct? or end of year. @sangwook96 Please update if I am wrong or there is an update.
