### ISSUE TITLE
Visual Studio 2022 version 17.3.0 Preview 3.0 breaks Maui Tizen builds

### ISSUE THREAD

**Issue by veikkoeeva** [Samsung/Tizen.NET#188]
It may be the Microsoft repo is the correct one to report this, please do redirect if so. I updated previous latest Visual Studio to [Visual Studio 2022 version 17.3.0 Preview 3.0](https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#17.3.0-pre.3.0) and it broke Maui builds giving the following symptoms:

![kuva](https://user-images.githubusercontent.com/5158694/178578726-3834c18a-828e-4377-9454-b617992245ff.png)

And from the build Console output
> 1>C:\<path>.csproj : error NU1102: Unable to find package Microsoft.Maui.Controls.Runtime.tizen with version (= 6.0.408)
1>C:\<path>.csproj : error NU1102:   - Found 4 version(s) in nuget.org [ Nearest version: 6.0.400 ]
1>C:\<path>.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
1>C:\<path>.csproj : error NU1102:   - Found 0 version(s) in C:\Program Files\dotnet\library-packs
1>C:\<path>.csproj : error NU1102: Unable to find package Microsoft.Maui.Core.Runtime.tizen with version (= 6.0.408)
1>C:\<path>.csproj : error NU1102:   - Found 4 version(s) in nuget.org [ Nearest version: 6.0.400 ]
1>C:\<path>.csproj: error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
1>C:\<path>.csproj: error NU1102:   - Found 0 version(s) in C:\Program Files\dotnet\library-packs
1>C:\<path>.csproj : error NU1102: Unable to find package Microsoft.Maui.Essentials.Ref.tizen with version (= 6.0.408)

And so on.

**Comment by sung-su** [comment]
Hello,
Could you share your `dotnet --version` and `dotnet workload list` results on your machine?
That would be very helpful in reproducing the problem.

**Comment by veikkoeeva** [comment]
> Hello, Could you share your `dotnet --version` and `dotnet workload list` results on your machine? That would be very helpful to reproducing the problem.

Yes.

> dotnet --version
> 6.0.400-preview.22330.6

> dotnet workload list
> 
| Installed Workload Ids | Manifest Version | Installation Source |
| - | - | - |
| maui-tizen |                 6.0.408/6.0.300          |        SDK 6.0.400 |
| tizen           |                    7.0.400-preview.1.0/6.0.400   |   SDK 6.0.400 |
| android       |              32.0.424/6.0.300          |       VS 17.3.32708.82 |
| maui-windows |               6.0.408/6.0.300     |             VS 17.3.32708.82 |
| maui-ios           |         6.0.408/6.0.300          |        VS 17.3.32708.82 |
| maui-maccatalyst |           6.0.408/6.0.300   |               VS 17.3.32708.82 |
| maccatalyst           |      15.4.430/6.0.400     |            VS 17.3.32708.82 |
| ios                        | 15.4.430/6.0.400          |       VS 17.3.32708.82 |
| maui-android        |        6.0.408/6.0.300   |               VS 17.3.32708.82 |


It turns out I was a bit hasty yesterday to report this. When I create a new project and add Tizen to compile targets I am again able to compile it. I also went to `Tools` -> `Options...` -> `Tizen` and enabled the workload again (even if looked like being enabled). When this works, the old project with Tizen workload still does not. I might need to diff the `.csproj` file and maybe look into source code to find out what's the reason. Removing `bin` and `obj` directories do not seem to make a difference.

To be honest, I'm not sure if I have time dig into this particular issue other than write here for wider audience this is how I got Tizen workload to compile again in Maui with a fresh, new Maui project. I'll add more if/when I find out more.

As an aside, I'm blocked to try to debug by
> EP1700: The recipe file "\MauiWebView\MauiWebView\bin\Debug\net6.0-tizen\tizen-x86\MauiWebView.build.appxrecipe" does not exist. You may need to build your project.
2Deployment of the application to the target device failed.

as noted also at https://github.com/Samsung/Tizen.NET/issues/185#issuecomment-1171618613.

**Comment by veikkoeeva** [comment]
I noticed again one odd thing with this existing project.

![kuva](https://user-images.githubusercontent.com/5158694/178661185-0361e282-d392-4840-a755-bcdca4d76944.png)

But if I add `global.json` to the previous project with

`{
  "sdk": {
    "version": "6.0",
	"rollForward": "latestFeature",
	"allowPrerelease": true
  }
}`

I can compile also the Tizen workload. But I can't Debug any targets, not even the Windows one, with that error message. Looking through https://github.com/dotnet/maui/issues/ and https://github.com/microsoft/WindowsAppSDK/issues/ I see there are issues with a similar error message.

**Comment by sung-su** [comment]
I'm glad your workload isn't a problem.
Some kind of debugging issues, similar to what you mentioned, will be fixed and applied the next version `vs-tools-for-tizen`.
I will try to update the related information in the path below.
https://github.com/Samsung/Tizen.NET/wiki/Known-Issues

**Comment by veikkoeeva** [comment]
@sung-su It may be this started since the debugger process holds locks on resources (e.g. files) even if VS is closed. Then something may go wrong in a way or another during updates. I'm not sure, but took a quick stab at it when I noticed this.
