### ISSUE TITLE
Unable to run .NET MAUI sample application on emulator

### ISSUE THREAD

**Issue by tsjdev-apps** [Samsung/Tizen.NET#204]
I've installed first `Tizen Studio` and also the extension of Tizen for Visual Studio. In the options I've configured everything and installed the workload. Now I'm booting the Emulator `M-6.5-x86` and I'm trying to build the application via the Terminal with the following command: `dotnet build -t:Run -f net6.0-tizen`

The app is than available on the emulator and I can see the splashscreen but the application is than closing directly. Any thoughts on how to be able to run the sample .NET MAUI application on the Tizen emulator?

**Comment by rookiejava** [comment]
Thank you for reaching out. As mentioned in the [known issues page](https://github.com/Samsung/Tizen.NET/wiki/Known-Issues), tizen emulator supporting .NET 6 and .NET MAUI has not yet been officially released. It is expected to be avaulable when Tizen 7.0 is announced next month. Please wait until then. Thanks!

**Comment by rookiejava** [comment]
Tizen 7.0 emulator is now available. Thank you for your patience! ❤️ 

Please download and install Tizen Studio 5.0 [here](https://developer.tizen.org/development/tizen-studio/download).
