### ISSUE TITLE
Where is TV Extensions-7.0?

### ISSUE THREAD

**Issue by talebi** [Samsung/Tizen.NET#213]
I cannot find the latest tv extensions v7.0 in the package manager. I can see mobile/wearable 7.0

Has it been released yet? if not what is the ETA?

**Comment by rookiejava** [comment]
Hi @talebi,
Yes. The TV Extension 7.0 hasn't been released yet. We will update you as soon as the schedule is confirmed. 
Thanks,

**Comment by talebi** [comment]
@JoonghyunCho why is this marked as completed? the tv extensions 7.0 is nowhere to be seen

**Comment by JoonghyunCho** [comment]
Hello @talebi, Sorry for the closing. I assumed the answer has been made for your issue.
TV extenion v7.0 is expected to be released on the early January 2023.

**Comment by JoonghyunCho** [comment]
@talebi Just so you know, TV extension v7.0 is out :)
