### ISSUE TITLE
Tizen Extension for Visual Studio. When the IDE starts, scripts are run always

### ISSUE THREAD

**Issue by DIMANRUS** [Samsung/Tizen.NET#218]
Hello. After installing the Tizen extension for Visual Studio, a message always appears when VS is launched about running three scripts as an administrator (screenshots are attached). One of them is workload-install.ps (in files.zip) , which apparently tries to install Tizen Workload. This is very annoying, why is this done at every startup? And if you open Visual Studio completely, then you can see a message at the bottom about the completion of the installation of Tizen Workload.
[files.zip](https://github.com/Samsung/Tizen.NET/files/10125548/files.zip)

![Screenshot_20221130_080326](https://user-images.githubusercontent.com/41239551/204862968-f51547c6-49af-45f3-b0ce-dd11677afb12.png)
![photo_2022-11-30_20-04-55](https://user-images.githubusercontent.com/41239551/204862971-59b22676-b892-485a-8106-1db068d7a08a.jpg)
![photo_2022-11-30_20-05-00](https://user-images.githubusercontent.com/41239551/204862976-5251c115-7371-45d0-8f06-5b07623fefcb.jpg)
![photo_2022-11-30_20-04-57](https://user-images.githubusercontent.com/41239551/204862977-c9358bb1-ea75-443e-9e67-a0c1b7686370.jpg)

**Comment by rookiejava** [comment]
@sangwook96-lee @winstone77 I'd appreciate it if you could share the detailed information for this situation.

**Comment by JoonghyunCho** [comment]
@DIMANRUS Sorry for annoying. We will try to avoid the situation.
@sangwook96-lee Please check if we can add a pre-step which decide if the installation step is required.

**Comment by sangwook96** [comment]
@JoonghyunCho 
HI, Thanks for informing me.
Sure, we will check it soon and update it again
Thanks

**Comment by MartinZikmund** [comment]
This is also happening to me. Is there a workaround for it?

**Comment by MartinZikmund** [comment]
Can this be prioritized please? It causes three confirmation popups for every Visual Studio launch, which is really painful when working on multiple different projects at once.

**Comment by sung-su** [comment]
@sangwook96 Any updates?

**Comment by billybooth** [comment]
Yes, this is terrible.

**Comment by sangwook96** [comment]
Hi, all
We have not checked it yet, Sorry for that.
We will check it and update our comments again.
Thanks

**Comment by sangwook96** [comment]
Hi, all
Simply, I updated my comment like the one below that.

Tizen.NET VS plugin(vs plugin) tries to download the file from there,https://github.com/Samsung/Tizen.NET/blob/main/workload/scripts/workload-install.ps1
and try to install Tizen.NET workload on the host pc.
When an installation time, the UAC of Windows asked the user if the software is known software or not.
They are the alert windows.

To avoid it, could you follow the below steps as a workaround?
https://windowsreport.com/do-you-want-to-allow-this-app-to-make-changes-to-your-device/
5. Now drag the bar slider to Never notify.

Thanks

**Comment by DIMANRUS** [comment]
@sangwook96 Is it necessary to install the workload through a script? Maybe just ask the user to do it himself? Or is there something I don't understand?

**Comment by sangwook96** [comment]
@DIMANRUS 
Hi
Thank you very much for updating your question

First, we thought that by adding the install script to the Tizen VS plugin, it's better for a user to give convenient usage.
As you know, the origin Tizen workload files are on https://github.com/Samsung/Tizen.NET/tree/main/workload/scripts
If you want to install it directly, you can follow the installation guide.

Sorry, I am not sure if my answer is correct for you
If you have anything more, please update your questions again.
Thanks

**Comment by MartinZikmund** [comment]
I would be happy with any solution that does not cause the three UAC prompts at the startup. Especially when the workloads are already installed, there is no need to prompt the user each time VS is started. Can the plugin be updated to avoid this?

**Comment by billybooth** [comment]
It would be far better for the user to install the workload as a prerequisite (or have the extension complain if the workload cannot be found). Launching an install script multiple with elevated permissions every time Visual Studio opens is more than a small annoyance.

**Comment by sangwook96** [comment]
Hi, All
Thank you very much for updating your questions.
We are talking about it internally again.
Once we have a new solution, we will update it again.
Thanks

**Comment by JoonghyunCho** [comment]
We have raised the priority of this painful issue, and expect to release the improved version soon.

**Comment by arvind84** [comment]
Any update related to this issue?

**Comment by DIMANRUS** [comment]
Thanks. With version extension 3.8.0.0 problem solved.
