### ISSUE TITLE
Using MAUI on Tizen 5.5

### ISSUE THREAD

**Issue by glorantq** [Samsung/Tizen.NET#219]
Is there any way to run MAUI apps on a TV running Tizen 5.5? I've succeeded in running other .NET apps, but my MAUI project only builds with the Tizen SDK version set to 7. Is there any way to make this work?

**Comment by JoonghyunCho** [comment]
Hello @glorantq. Unfortunately, MAUI apps are currently not available on Tizen  5.5. MAUI apps including dotnet6 is available on Tizen 7.0 which is released last month.
