### ISSUE TITLE
When Tizen workload is installed, `dotnet workload update` fails

### ISSUE THREAD

**Issue by MartinZikmund** [Samsung/Tizen.NET#223]
When `tizen` .NET workload is installed:

![image](https://user-images.githubusercontent.com/1075116/209302991-10086624-206e-4a15-9f44-93e6cf2fb495.png)

The workload update `dotnet workload update` fails and gets rolled-back:

![image](https://user-images.githubusercontent.com/1075116/209303111-5df4c4f2-179e-485e-a421-444c6ae72462.png)

To update or install any workload, I always have to uninstall `tizen` first, otherwise every change gets rolled-back (even non-Tizen changes)

**Comment by sung-su** [comment]
Hello,
This problem can be bypass through the `--skip-manifest-update` option.

**Comment by MartinZikmund** [comment]
Is there a way the `--skip-manifest-update` could be avoided? It is quite annoying and developers will necessarily hit this and see it as a bug

**Comment by sung-su** [comment]
This is a problem caused by different providers,
(only Tizen workload is provided by Samsung)
we are trying to solve this update problem.
