### ISSUE TITLE
I can not create a new MAUI Project and choose Tizen as target 

### ISSUE THREAD

**Issue by innovativesolutionseg** [Samsung/Tizen.NET#224]
I Have this error **failed to restore** when I Uncomment this line
 <TargetFrameworks>$(TargetFrameworks);net7.0-tizen</TargetFrameworks> 

And I Have these errors with the rebuild 

**Severity Code Description Project File Line Suppression State
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-tizen**

And

**Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1139	The target platform identifier Tizen was not recognized.**

Note: Tizen SDK, Tizen Extention on Visual Studio, And Tizen workload installation is successfully done.

**Comment by innovativesolutionseg** [comment]
I am grateful for your support
**~$ dotnet --info**
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.113 [C:\Program Files\dotnet\sdk]
  6.0.308 [C:\Program Files\dotnet\sdk]
  7.0.101 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found


**~$ dotnet workload list**

Workload ID                Description
-----------------------------------------------------------------------------------
android                    .NET SDK Workload for building Android applications.
ios                        .NET SDK Workload for building iOS applications.
maccatalyst                .NET SDK Workload for building MacCatalyst applications.
macos                      .NET SDK Workload for building macOS applications.
maui                       .NET MAUI SDK for all platforms
maui-android               .NET MAUI SDK for Android
maui-desktop               .NET MAUI SDK for Desktop
maui-ios                   .NET MAUI SDK for iOS
maui-maccatalyst           .NET MAUI SDK for Mac Catalyst
maui-mobile                .NET MAUI SDK for Mobile
maui-tizen                 .NET MAUI SDK for Tizen
maui-windows               .NET MAUI SDK for Windows
runtimes-windows           workloads/runtimes-windows/description
runtimes-windows-net6      workloads/runtimes-windows-net6/description
tvos                       .NET SDK Workload for building tvOS applications.
wasm-experimental          workloads/wasm-experimental/description
wasm-tools                 .NET WebAssembly build tools
wasm-tools-net6            .NET WebAssembly build tools

**Comment by JoonghyunCho** [comment]
Looks like you don't have Tizen workload installed on your latest dotnet sdk 7.0.102.
You may want to install Tizen workload with one of the followings:
  - Launch Visual Studio if you have VS Tools for Tizen Extension installed on your VS.
  - Manually download the install script and execute.  
    `Invoke-WebRequest 'https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.ps1' -OutFile 'workload-install.ps1';
./workload-install.ps1`

Checkout https://github.com/Samsung/Tizen.NET/wiki/Installing-Tizen-.NET-Workload for the details.
If Tizen workload is installed properly you would be able to see `tizen` in your workload list.

Or you can set the global.json to specify the specific dotnet version that has Tizen workload installed.

**Comment by innovativesolutionseg** [comment]
I appreciate your taking the time.
I did manually download the installation for Tizen workload, but I have this message "Check Tizen Workload for sdk 6.0.308
Tizen Workload 7.0.304 version is already installed."

**Comment by sung-su** [comment]
Please try this command `./workload-install.ps1 -u`.

**Comment by veikkoeeva** [comment]
I have the workload installer downloaded and run locally and the VS extension installed. Still whenver I open Visual Studio, Windows pops up a workload installer script prompt asking permission to run it. I don't know how to remove this prompt. It originates from Tizen.

**Comment by sung-su** [comment]
@veikkoeeva 
same as #218

**Comment by veikkoeeva** [comment]
By the way, I add https://github.com/dotnet/maui/issues/8035#issuecomment-1398861065 here too. It may be this is related to the initial issue. I bundled this script thing, since I didn't know if they're related.

**Comment by sangwook96** [comment]
@veikkoeeva Hi,
https://github.com/Samsung/Tizen.NET/issues/218 was updated some comments, you can check it,too.
