### ISSUE TITLE
Can't install Tizen Workload

### ISSUE THREAD

**Issue by BullShark** [Samsung/Tizen.NET#225]
I don't have the option to install Tizen Workload.

![image](https://user-images.githubusercontent.com/1526595/211676426-8ad3d197-bdf2-4813-a388-9591297a078b.png)
### 

Also I had these errors.

![image](https://user-images.githubusercontent.com/1526595/211676938-74ca3ea5-7d67-4159-a36e-c6de93204cd2.png)

![image](https://user-images.githubusercontent.com/1526595/211676956-b028e065-ba2c-4c30-9352-ee097c518af3.png)

**Comment by JoonghyunCho** [comment]
1. Sorry for the outdated picture on the guide. The current version of the VSIX doesn't have the installation button. 
2. The installation process runs in the background process automatically when the VS is launched.
3. Tizen baseline sdk path needs to be set. If it is not installed on your machine, please take a look at the [guide](https://docs.tizen.org/application/vstools/install/#install-tizen-baseline-sdk) or just download the installer [here](http://download.tizen.org/sdk/Installer/Latest/)

@sangwook96-lee Can you tell when the Tizen Workload script copy could be failed?

**Comment by sangwook96** [comment]
@JoonghyunCho 
Hi,Sorry,
I have not checked your message till now.
When VS launches, it tries to copy the Tizen workload.
