### ISSUE TITLE
Cannot Connect to Network on MAUI Project and Tizen

### ISSUE THREAD

**Issue by ahmadun** [Samsung/Tizen.NET#228]
My project use .net MAUI .net6, currently I debug the program to android and windows working normally to retrieve data from network.
but when try to debug in Tizen emulator, the app cannot get the api data from network

**Comment by sung-su** [comment]
Hello, @ahmadun 
Does the app include the `http://tizen.org/privilege/internet` privilege ?
Please refer [here](https://www.tizen.org/privilege).

Thanks.

**Comment by ahmadun** [comment]
The problem solved.
Thank you
