### ISSUE TITLE
Cannot deploy to Samsung TV

### ISSUE THREAD

**Issue by ahmadun** [Samsung/Tizen.NET#230]
I am currently try to deploy the apps on Samsung TV T6500, the step tried so far

first, Set Devices to Developer mode.
1. Create certificate with Samsung and install to Devices from Tizen Device Manager
2. Try to install from Tizen Device Manager, but no result on TV
3. Try to install from CLI with >tizen install -n app.tpk. but error with [not allowed...]

**Comment by sung-su** [comment]
Hi, ahmadun
MAUI apps including dotnet6 is available on Tizen 7.0.

Thanks.
