### ISSUE TITLE
7.0.200 not download. Error 404.

### ISSUE THREAD

**Issue by DIMANRUS** [Samsung/Tizen.NET#232]
Hello. I am executing the script according to the instructions (https://github.com/Samsung/Tizen.NET/wiki/Installing-Tizen-.NET-Workload ) 7.0.105 was successfully installed, but 7.0.200 received a 404 error from the server
![image](https://user-images.githubusercontent.com/41239551/221194208-e7b18924-f35e-44a2-9c74-778bef2e3078.png)

**Comment by sung-su** [comment]
`Tizen workload version 7.0.105` is for `dotnet sdk version 7.0.200`. 
Please check [here](https://github.com/Samsung/Tizen.NET/releases/tag/v7.0.105).
Thank you.

**Comment by DIMANRUS** [comment]
Thanks
