### ISSUE TITLE
Tizen TV Samsung 7.0 not starting

### ISSUE THREAD

**Issue by DIMANRUS** [Samsung/Tizen.NET#233]
Hello. Why is there an error when starting the TV emulator? The rest of the emulators are running.
![image](https://user-images.githubusercontent.com/41239551/221339890-53075df2-8698-43c4-819d-4d265848d2ed.png)

**Comment by sung-su** [comment]
@sangwook96-lee 
Could you take a look at this ?

**Comment by sangwook96** [comment]
Hello, 
Thanks for asking it.
Now, Tizen TV emulator does not support whpx option.
Instead of it, it use haxm driver.
Please follow the guide. 

https://developer.tizen.org/development/tizen-studio/download/installing-tizen-studio/hardware-accelerated-execution-manager

Thanks

**Comment by DIMANRUS** [comment]
> Hello, 
> Thanks for asking it.
> Now, Tizen TV emulator does not support whpx option.
> Instead of it, it use haxm driver.
> Please follow the guide. 
> 
> https://developer.tizen.org/development/tizen-studio/download/installing-tizen-studio/hardware-accelerated-execution-manager
> 
> Thanks
> 

Thanks for the reply

**Comment by vankhoa01** [comment]
@sangwook96 : I have similar this issue.
But It occurs on Macbook M1
Could you pls help to take a look my issue here https://github.com/Samsung/Tizen.NET/issues/265 ?
Thank you so much

**Comment by sangwook96** [comment]
@vankhoa01 ,
https://github.com/Samsung/Tizen.NET/issues/265: I answered it there.
Case 1)Tizen TV emulator: We do not support Whpx otpion.(environment)
Case 2) Tizen public emulator: We can support whpx on Intel cpu.
Case 3) All of the tizen emulators: They are not working on the M1/M2.
Thank you so much.

**Comment by sangwook96** [comment]
@vankhoa01
Hi,
You can use the latest tizen sdk with the below them.
https://developer.tizen.org/ - TizenSDK 5.5  for Tizen 8.0 
https://marketplace.visualstudio.com/items?itemName=tizen.VSToolsTizen2022  => VS for Tizen extension
