### ISSUE TITLE
.NET Development is not supported on the connected device model

### ISSUE THREAD

**Issue by dmsch** [Samsung/Tizen.NET#236]
### Steps to reproduce:

1. Create Visual Studio Project "Blank App (Tizen.NUI)", .NET 6.0
2. Connect to TV using the Device Manager
3. Debug/Run Project on TV

### Error: 
`###############.NET Development is not supproted on the connected device model###############`

### Question:
Is there a misconfiguration, or does the display not support .NET applications at all?
We want to develop .NET applications for digital signage screens, which "Samsung Smart Signage" models are suitable for this?

### Details:
Development Environment: Visual Studio 2022
Device: Samsung QM43B
Platform: tv-6.5
Version: S-PTMWWC-1090.2

**Comment by sung-su** [comment]
@dmsch 
.NET6 is available on Tizen 7.0.
Thank you

**Comment by dmsch** [comment]
@sung-su 
Thanks for your answer.
We develop only for SSSP devices from Samsung.
Are these also supported by Tizen.NET?
