### ISSUE TITLE
Tizen tools generate `workload-install.ps1` next to `.sln`

### ISSUE THREAD

**Issue by MartinZikmund** [Samsung/Tizen.NET#240]
When Tizen tools are installed in Visual Studio, a file `workload-install.ps1` is always generated in the solution folder (even though everything is already installed). I don't see a reason why this file could not be generated in %TEMP% folder instead.

**Comment by sung-su** [comment]
@MartinZikmund 
Could you share more information for reproduce ? 
e,g, VS version, VS tools for Tizen extension version, dotnet sdk version

**Comment by MartinZikmund** [comment]
Tizen plugin in VS: 3.8.0.0
VS: 17.6.0
.NET SDK: 7.203

**Comment by sung-su** [comment]
@sangwook96-lee 
Please take a look on this situation and give some feedback. Thanks!

**Comment by MartinZikmund** [comment]
@sung-su this is still happening very often, can you please reopen?

**Comment by MartinZikmund** [comment]
Everytime a solution is opened, this happens:
<img width="968" alt="image" src="https://github.com/Samsung/Tizen.NET/assets/1075116/874143fe-05db-4386-a67c-dc89eae8010c">

**Comment by sung-su** [comment]
Hello, @MartinZikmund 
I apologize for your inconvenience.

Is there a reason why you have to use dotnet SDK 6.0.2xx version ?
If you are still using 6.0.2xx, I recommend updating the SDK.
You should use to at least the latest band (6.0.4xx) or using the SDK provided by VS.

Thanks

**Comment by MartinZikmund** [comment]
@sung-su I am targeting .NET 7 latest. On my device I have quite a few SDKs installed, but I am not using 6.0.2xx anywhere - 
![image](https://github.com/Samsung/Tizen.NET/assets/1075116/028286e8-e357-4ed8-99ce-7206120a9b81)

The default SDK I am using is 7.0.400

**Comment by sung-su** [comment]
Could you update the version of `VS tools for Tizen` on VS extension ?
It could cause a problem.

**Comment by sung-su** [comment]
@dkson95 
Please take a look on this situation and give some feedback. 
Thanks!

**Comment by dkson95** [comment]
okay, let me check n update - though it was located under `c:\Windows\System32\` in my env.

**Comment by dkson95** [comment]
Dear @MartinZikmund 
would you once check latest VS 2022 tools for Tizen on https://marketplace.visualstudio.com/items?itemName=tizen.VSToolsTizen2022 (after uninstall current version) ?

According to the check, we always download the `workload-install` file to `%{tizen-studio-path}\tools` folder
Otherwise, you need to check the `%{tizen-studio-path}` loc. : set by `Tools > Options > Tizen > Tools > Tool Path`

Thank you!

**Comment by ahoke-cr** [comment]
Changing the tool path seems to have stopped the addition of the PS script to my solutions, but it's still obnoxious this occurs in the first place. Is it possible to specify a default tool directory, like something in `AppData/Local/Tizen`?
