### ISSUE TITLE
Workload installation failed. Tried reinstalling several times but facing the same issue.

### ISSUE THREAD

**Issue by Santhu1459** [Samsung/Tizen.NET#242]
<img width="950" alt="image" src="https://github.com/Samsung/Tizen.NET/assets/106695859/6ba72a3a-f443-40a3-810a-9c7b708570bd">
<img width="380" alt="image" src="https://github.com/Samsung/Tizen.NET/assets/106695859/7bff2cd9-a1b3-4624-aa5e-d6ab44b0949a">
<img width="665" alt="image" src="https://github.com/Samsung/Tizen.NET/assets/106695859/f8bd0cc8-f7fa-499a-80f6-9dad981eed29">
<img width="524" alt="image" src="https://github.com/Samsung/Tizen.NET/assets/106695859/e3c97d08-43e3-44be-b1c0-ad9e3a8ee09a">
<img width="714" alt="image" src="https://github.com/Samsung/Tizen.NET/assets/106695859/63d5b341-3633-40be-b02d-c72f5cc820c0">
<img width="250" alt="image" src="https://github.com/Samsung/Tizen.NET/assets/106695859/66ce849b-bd8f-4b78-91df-399d680e4807">

**Comment by Santhu1459** [comment]
<img width="601" alt="image" src="https://github.com/Samsung/Tizen.NET/assets/106695859/9e544f9a-2a08-4fd4-812e-c7c9df1d30b4">

**Comment by JoonghyunCho** [comment]
I am not sure what you tried to do at the first image, but Tizen doesn't provide the msi file.
If you want to remove and reinstall Tizen workload, I think you have to remove tizen workload and manually remove `samsung.net.sdk.tizen` folder under for example `C:\Program Files\dotnet\sdk-manifests\7.0.200` path.
Then, VS extension will check and install the proper workload when VS is launched.

**Comment by Santhu1459** [comment]
@JoonghyunCho  - As you mentioned, deleted that folder. Uninstalled and then Installed .Net Tizen Workload again but getting the below exception while running the application.
![image](https://github.com/Samsung/Tizen.NET/assets/106695859/5ecf0574-a4e6-479d-9695-a132fe0e53b7)

**Comment by veikkoeeva** [comment]
At least with Microsoft Visual Studio Community 2022 (64-bit) Version 17.7.0 Preview 1.0 (latest preview as of this writing) and .NET 8 installed this same issue happens when a Maui application targets .NET 8 (with and without global.json). This also happens with `dotnet build`. Even when `<TargetFrameworks>` does not contain `net8.0-tizen`, which I find strange.

**Comment by Santhu1459** [comment]
Any updates on this issue

**Comment by JoonghyunCho** [comment]
Sorry for the late reply. Is this happening during the debug run? Or the app just crash at launching time?
Is your app targets `net6.0-tizen` and you use 7.0 version of the emulator? for example 7.0 mobile?
Please check the emulator platform version
<image src="https://github.com/Samsung/Tizen.NET/assets/14328614/55baa5a0-8c5e-4eea-a577-0e5956f65a36" height="300" />

**Comment by Santhu1459** [comment]
It is happening during debug run. app targets net7.0-tizen and using 7.0 mobile

**Comment by Santhu1459** [comment]
Working with net6.0-tizen but fails in net7.0-tizen

**Comment by JoonghyunCho** [comment]
Oh I see. dotnet runtime is embedded in the Tizen platform, and Tizen 7.0 is released with NET6.
So the latest target framework that is supported on Tizen devices is `net6.0-tizen`.
There is no public emulator or targets that support `net7.0-tizen` yet..
