### ISSUE TITLE
Show input keyboard

### ISSUE THREAD

**Issue by OmidID** [Samsung/Tizen.NET#247]
Hello,

Currently, I implementing Avalonia for Tizen and I need your assist.

I need to show the keyboard and I realized `InputMethodContext` has obsoleted the contractor. What I found in TizenFX, the `InputMethodContext` is used only for the text field, in our case we done the implementation of input inside the Avalonia core. 
How can I show the keyboard without text input?

Thanks in advance.

**Comment by OmidID** [comment]
By the way, if you are interested you can see the video at https://twitter.com/AvaloniaUI/status/1671617269774929920 
and this is the implementation: https://github.com/OmidID/Avalonia/tree/features/tizen/src/Tizen/Avalonia.Tizen
Once I am done with the implementation, It will merge to upstream.

**Comment by JoonghyunCho** [comment]
Hello @OmidID ! It's great to hear that you are implemention Avalonia for Tizen! so cool!
I know there is one method  `Tizen.NUI.BaseComponents.View.KeyInputFocus` that you can  show the keyboard. 
You can just set your `view.KeyInputFocus = true` to show the soft keyboard. This is btw not shown in your intellisence or docs because it is set as EditorBrowsableState.Never.
Please see if this is what you want or let me know again!
Thanks!

**Comment by OmidID** [comment]
Thanks a lot for helping.

I tried this solution but had no success. When I set it to true I cannot see the keyboard popup. 
After showing the keyboard I need some functionalities such as selecting text, predicting words, hiding and showing, setting position, change the type of keyboard such as (number, alphabetic, and sensitive). and it would be great to set the return key type.

For the moment I placed an input field and hide it in the back and outside of the screen. And I try to sync it with the selected text. I am not sure if this is a good idea. but it works at least.

Thanks again.

**Comment by OmidID** [comment]
@JoonghyunCho I need your help again. It is tricky to implement input. 
I cannot find a solution to show the keyboard and get the key event on the custom view. And I cannot find a solution to get control of the keyboard.

I try to forward keyboard events from TextEditor to my custom, but key events are not performed while the keyboard focuses on a text editor.

I really needs help please :)

Thanks a lot.
