### ISSUE TITLE
Unable to install workload - BlobNotFoundThe specified blob does not exist.

### ISSUE THREAD

**Issue by PerfectlyFineCode** [Samsung/Tizen.NET#248]
Hi!

I'm trying to install the workload but unable to do so.
```
PS C:\Windows\system32> Invoke-WebRequest 'https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.ps1' -OutFile 'workload-install.ps1';
./workload-install.ps1 -v 7.0.105

Check Tizen Workload for sdk 8.0.100-preview.5.23303.2
Installing Samsung.NET.Sdk.Tizen.Manifest-8.0.100-preview.5/7.0.105 to C:\Program Files\dotnet\sdk-m
anifests\8.0.100-preview.5...
Failed to install Tizen Workload for sdk 8.0.100-preview.5.23303.2
BlobNotFoundThe specified blob does not exist. RequestId:7ac3f4db-201e-0015-52b3-a7aa44000000 Time:2
023-06-25T22:23:17.8311554Z

Done
```

Any reason for this?

Now when i do `dotnet workload list` I get this error
```
PS D:\Coding\MAUI\RecipeManager> dotnet workload list

Unhandled exception: System.Collections.Generic.KeyNotFoundException: The given key 'tizen' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.GetManifestFromWorkload(WorkloadId workloadId)
   at Microsoft.DotNet.Workloads.Workload.List.WorkloadListCommand.<Execute>b__5_2(KeyValuePair`2 workload)
   at Microsoft.DotNet.Cli.PrintableTable`1.<>c__DisplayClass9_0.<CalculateColumnWidths>b__0(Column c)
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Cli.PrintableTable`1.CalculateColumnWidths(IEnumerable`1 rows)
   at Microsoft.DotNet.Cli.PrintableTable`1.PrintRows(IEnumerable`1 rows, Action`1 writeLine)
   at Microsoft.DotNet.Workloads.Workload.List.WorkloadListCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by sung-su** [comment]
Hello @PerfectlyFineCode 

1. Could you check your dotnet sdk version ? It seems that the version is not matched.
  `PS> dotnet --version` 
2. You don't need to use the `-v` option. Just a script call is enough.
3. To restore the current abnormal state, a forced folder deletion may be required.
  `C:\Program Files\dotnet\sdk-manifests\[version]\samsung.net.sdk.tizen`
4. dotnet sdk 8.0 is a pre-release. Please use officially released dotnet sdk.

Thank you

**Comment by PerfectlyFineCode** [comment]
> Hello @PerfectlyFineCode
> 
> 1. Could you check your dotnet sdk version ? It seems that the version is not matched.
>    `PS> dotnet --version`
> 2. You don't need to use the `-v` option. Just a script call is enough.
> 3. To restore the current abnormal state, a forced folder deletion may be required.
>    `C:\Program Files\dotnet\sdk-manifests\[version]\samsung.net.sdk.tizen`
> 4. dotnet sdk 8.0 is a pre-release. Please use officially released dotnet sdk.
> 
> Thank you

I use `8.0.100-preview.5.23303.2`
And here are my workloads after installing the VS extension.
```

Installed Workload Id      Manifest Version                               Installation Source
------------------------------------------------------------------------------------------------------------------
android                    34.0.0-preview.5.312/8.0.100-preview.5         SDK 8.0.100-preview.5, VS 17.6.33717.318
tizen                      7.0.110/8.0.100-preview.5                      SDK 8.0.100-preview.5
wasm-tools-net6            8.0.0-preview.5.23280.8/8.0.100-preview.5      SDK 8.0.100-preview.5
wasm-tools                 8.0.0-preview.5.23280.8/8.0.100-preview.5      VS 17.6.33717.318
maui-windows               8.0.0-preview.5.8529/8.0.100-preview.5         VS 17.6.33717.318
ios                        16.4.8525-net8-p5/8.0.100-preview.5            VS 17.6.33717.318
maccatalyst                16.4.8525-net8-p5/8.0.100-preview.5            VS 17.6.33717.318
maui-maccatalyst           8.0.0-preview.5.8529/8.0.100-preview.5         VS 17.6.33717.318
maui-ios                   8.0.0-preview.5.8529/8.0.100-preview.5         VS 17.6.33717.318
maui-android               8.0.0-preview.5.8529/8.0.100-preview.5         VS 17.6.33717.318
```

Here's the csproj target framework
```
    <TargetFrameworks>$(TargetFrameworks);net7.0-tizen</TargetFrameworks>
```
When building I seem to get this error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1139	The target platform identifier tizen was not recognized.	MauiApp4	C:\Program Files\dotnet\sdk\7.0.304\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	112	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-tizen	MauiApp4	D:\Coding\MAUI\MauiApp4\MauiApp4\MauiApp4.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-tizen	MauiApp4	D:\Coding\MAUI\MauiApp4\MauiApp4\MauiApp4.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-tizen	MauiApp4	D:\Coding\MAUI\MauiApp4\MauiApp4\MauiApp4.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-tizen	MauiApp4	D:\Coding\MAUI\MauiApp4\MauiApp4\MauiApp4.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net7.0-tizen	MauiApp4	D:\Coding\MAUI\MauiApp4\MauiApp4\MauiApp4.csproj	1	
```
From what I've read it should be for .NET 7.0, but I've also tried .NET 6.0, still same error.

**Comment by sung-su** [comment]
Currently, `tizen` workload identifier only recognized on the official released dotnet sdk.
`8.0.100-preview.5.23303.2` is pre-release version.
This issue has being fixed and I recommended dotnet sdk 7.0 version.

If you have multiple versions of dotnet sdk installed, 
you can check the installation through the following options.
```
PS> ./workload-install.ps1 -u
```

**Comment by PerfectlyFineCode** [comment]
> Currently, `tizen` workload identifier only recognized on the official released dotnet sdk. `8.0.100-preview.5.23303.2` is pre-release version. This issue has being fixed and I recommended dotnet sdk 7.0 version.
> 
> If you have multiple versions of dotnet sdk installed, you can check the installation through the following options.
> 
> ```
> PS> ./workload-install.ps1 -u
> ```

Thank you!
This worked.

It can compile and all, but I can't seem to debug it.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP1700: The recipe file "D:\Coding\MAUI\MauiApp4\MauiApp4\bin\Debug\net6.0-tizen\tizen-x86\MauiApp4.build.appxrecipe" does not exist. You may need to build your project.	MauiApp5			
```
Is this an issue with MAUI itself or with Tizen SDK?
I saw that there are issues open about this specific issue. https://github.com/dotnet/maui/issues/8035

**Comment by sung-su** [comment]
@PerfectlyFineCode 
I am Sorry for your inconvenience.

@sangwook96-lee 
Please take a look on this and give some feedback.
Thank you

**Comment by PerfectlyFineCode** [comment]
Can you just use NuGet???
This is incredibly frustrating.
When I try to update or install a workload, it will error out because Tizen doesn't exist in NuGet.

![image](https://github.com/Samsung/Tizen.NET/assets/70201838/bf006b27-aac5-444a-9821-0541627d5a43)

**Comment by sung-su** [comment]
This is a problem caused by different providers,
(only Tizen workload is provided by Samsung)
we are trying to solve this update problem. 
You can bypass through the `--skip-manifest-update` option.

**Comment by sung-su** [comment]
@sangwook96-lee 
Please handover issues.
@dkson95 
Could you please take a look on this ?

**Comment by dkson95** [comment]
@PerfectlyFineCode sorry for the inconvenience.

1. Would you re-install workload https://github.com/Samsung/Tizen.NET/wiki/Installing-Tizen-.NET-Workload to check ? FYI, Visual Studio 2022 Tools for Tizen was released recently on https://marketplace.visualstudio.com/items?itemName=tizen.VSToolsTizen2022.

2. MAUI app : there is still deployment issue to be used by `tizen` (https://github.com/dotnet/maui/issues/8035) so, could you try using another templates (e.g., NUI app)

3. WHPX : You need to check the config on https://learn.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?pivots=windows#accelerating-with-hyper-v or check the command on Windows PowerShell

1) Check the configuration 
``` 
Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online
```
2) Enable Hyper-V & HypervisorPlatform
```
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
Enable-WindowsOptionalFeature -Online -FeatureName HypervisorPlatform -All
```

Otherwise, you need to switch off WHPX and enable HAX by installing HAXM driver.

Thank you!

**Comment by PerfectlyFineCode** [comment]
Not completed.

**Comment by HJLeee** [comment]
cc/ @winstone77
