### ISSUE TITLE
Clipboard API

### ISSUE THREAD

**Issue by OmidID** [Samsung/Tizen.NET#249]
Hello Again,

Following the Tizen implementation by Avalonia, We need to have access to the clipboard API.
https://github.com/AvaloniaUI/Avalonia/issues/6110

I did a search in the documentation and a little bit inside TizenFx, and I couldn't find anything. I need your help to find a solution to do 4 important possible operations set/get text and set/get data.

Thanks again for your help

**Comment by myroot** [comment]
We haven't Clipboard frameworks

But, Some component support to access clipboard with helper api 
refer this api 
https://github.com/Samsung/TizenFX/blob/5b30b4340dbe56b38cc3405f7c31226a6b867a1a/src/Tizen.NUI/src/public/BaseComponents/TextUtils.cs#L1186C15-L1186C15

**Comment by OmidID** [comment]
Thanks a lot, @myroot 
I will try to use that component for the clipboard. 

I can see we have only text not data such as images, Right?

**Comment by OmidID** [comment]
@myroot 
Do you think this is a good way: https://github.com/OmidID/Avalonia/commit/4420110dfac40f64956ef62a2088dbb58d4187a3

**Comment by myroot** [comment]
@OmidID 
Yes, good that's creative! actually I don't have a deep understanding of the behavior of this API, but your code seems to be working fine.

**Comment by OmidID** [comment]
Hello again @myroot 

It looks like this solution not working.
Any idea?

**Comment by OmidID** [comment]
@myroot Can you help me to solve the issue? 
Maybe I need to add any feature or permission?

**Comment by myroot** [comment]
It may not support on TV profile, 
I will report it to component owner

**Comment by myroot** [comment]
I had some test and I found some issue on https://github.com/OmidID/Avalonia/commit/4420110dfac40f64956ef62a2088dbb58d4187a3 this code

First, Selection of TextEditor is only available when view was attached on window.
So need to add a layer
``` c#
    public NuiClipboardImpl()
    {
        _textEditor = new TextEditor();
         Window.Instance.GetDefaultLayer().Add(_textEditor);
         _textEditor.LowerToBottom();
         _textEditor.Hide();
    }
```

Second. `SelectWholeText` seems a async method(it seems to need working of render side) so need a execute of render loop 
if you add any Delay call on `SetTextAsync` method it works

``` c#
        public async Task SetTextAsync(string text)
        {
            FocusManager.Instance.SetCurrentFocusView(_textEditor);
            _textEditor.Text = text;
            _textEditor.SelectWholeText();
            await Task.Delay(1);
            TextUtils.CopyToClipboard(_textEditor);
        }
```

**Comment by wonrst** [comment]
@OmidID
TextUtils's copy & paste APIs are only for text component.
It seems unreasonable to use it as a general Clipboard API.

Anyway, as @myroot explained, `SelectWholeText()`, `CopyToClipboard()`, and `PasteTo()` operate asynchronously, so there are several timing issues to consider.

And.. due to TV Profile constraints, it cannot cross between apps and only works within a single app.
What is your Tizen version?

**Comment by OmidID** [comment]
Thanks a lot for your replies.
OK. What I understand, is we do not have any option to have OS Level clipboard API. 
I am not targeting only TV. But mostly I do all tests on TV which is very important today.
I will perform tests and fingers crossed that I can finish with this and prepare the PR for merge.
