### ISSUE TITLE
Crash while checking permission

### ISSUE THREAD

**Issue by OmidID** [Samsung/Tizen.NET#250]
Hello,

I try to implement the sotrage provider feature for Avalonia https://github.com/AvaloniaUI/Avalonia/issues/6110
My app getting crashed while checking the permissions.

```
at Interop.PrivacyPrivilegeManager.CheckPermission(String privilege, CheckResult& result)
at Tizen.Security.PrivacyPrivilegeManager.CheckPermission(String privilege) in Tizen.Security.PrivacyPrivilegeManager.dll:token 0x6000007+0x0
```

```
Unable to load shared library 'libcapi-privacy-privilege-manager.so.0' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibcapi-privacy-privilege-manager.so.0.so: cannot open shared object file: No such file or directory
```

This is the code of how I did that: https://github.com/OmidID/Avalonia/blob/features/tizen/src/Tizen/Avalonia.Tizen/Platform/Permissions.cs

Thanks for helping.

**Comment by rookiejava** [comment]
Can you tell me about the environment you were tested in? Was it on a physical device or an emulator? What version was used, what profile was used, and so on?

**Comment by OmidID** [comment]
@rookiejava  If you can clone the repo (https://github.com/OmidID/Avalonia/tree/features/tizen) and run the `ControlCatalog.Tizen`. You can click on the menu `Dialog` on the left, it performs the permission check.



![image](https://github.com/Samsung/Tizen.NET/assets/956077/d9167160-7d17-406e-9943-773cf8678f63)

**Comment by rookiejava** [comment]
> This is the code of how I did that: ? https://github.com/OmidID/Avalonia/blob/features/tizen/src/Tizen/Avalonia.Tizen/Platform/Permissions.cs

I don't see any specific issues in the code you mentioned above, so I'm trying to clone the repo and run the `ControlCatalog.Tizen` apss myself to reproduce it. However, I'm having trouble building it. Is there any prerequisite or guide for building Avalonia locally?

**Comment by OmidID** [comment]
Great. 
You shouldn't have any issue to build Avalonia, 
Normally if you have dotnet6 and 4.71 should be fine.

If you still have issues to build maybe you can check this wiki: https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md and do not forget to use my repo feature branch https://github.com/OmidID/Avalonia/tree/features/tizen

Thanks a lot :)

**Comment by rookiejava** [comment]
Uppon further investigation, it apears that the `PrivacyPrivilegeManager` APIs are only supported on mobile and wearable profiles. Therefore, it would be advisable to make the necessary modifications to avoid using that APIs on the TV. I have submmited a [PR[(https://github.com/OmidID/Avalonia/pull/1), so please refer to it. Thanks.

And, I'll also request the relevant department to update the related documents (API reference, developer guide, and so on) appropriately to avoid any further confusion.

**Comment by OmidID** [comment]
Thank you so much for helping. :)
I am very glad that I see your PR.
