### ISSUE TITLE
Minimum Tizen version support

### ISSUE THREAD

**Issue by OmidID** [Samsung/Tizen.NET#251]
Hello,

I would like to have more information about the OS versioning and feature support.

For me important to know what is the dotnet6 minimum Tizen OS support. 

I try dotnet7 and I catch a crash on startup. Do we have the possibility to use dotnet7?

It looks like information about Family Hub is private, Which Tizen installed on Samsung's fridge? The same dotnet app with NUI will work on them?

**Comment by sung-su** [comment]
Hello, @OmidID 

`FamilyHub` is also support `.NET`.
You can check the `Tizen` version in setting app.

`.NET6` and `NUI` are available from `Tizen7.0`
`.NET7` is not supported yet.

Thanks

**Comment by OmidID** [comment]
Hello @sung-su 
Thanks for the information. Can I have the Tizen OS version market share statistics?

**Comment by sung-su** [comment]
I'm sorry, I don't understand exactly what your question means.
Do you need Tizen OS version information of Family Hub?

**Comment by OmidID** [comment]
I mean something like this:
https://gs.statcounter.com/ios-version-market-share/

Just a percentage will help me to know how much effort we need to support the older version or not.

**Comment by sung-su** [comment]
`Tizen` has different support versions depending on the type of device.
Most of all, the latest released Tizen OS version is `7.0`.
`.NET6` available from `Tizen7.0` also.
If your app is based on `.NET6`, there is no need to consider the previous version.

**Comment by OmidID** [comment]
Thanks a lot for the information.
