### ISSUE TITLE
WebView not work on TV. Black screen

### ISSUE THREAD

**Issue by DIMANRUS** [Samsung/Tizen.NET#253]
Hello. I created Xamarin.Forms Tizen project. But I tried it in NUI, ElmSharp and other templates, the same thing everywhere. I tested it on a mobile emulator, everything works there, but why doesn't it work on TV, just a black screen?

https://github.com/Samsung/Tizen.NET/assets/41239551/73b786c2-55f3-4acf-8241-b2bd93619fa9

https://github.com/Samsung/Tizen.NET/assets/41239551/97586358-db73-4deb-9d90-3b695a3270e8

![Снимок экрана 2023-08-27 091533](https://github.com/Samsung/Tizen.NET/assets/41239551/9c5d68ef-b972-48e6-a53b-91bef46de750)
![Снимок экрана 2023-08-27 091515](https://github.com/Samsung/Tizen.NET/assets/41239551/6666bb82-52ff-46da-9feb-641680e24aba)
![Снимок экрана 2023-08-27 091529](https://github.com/Samsung/Tizen.NET/assets/41239551/ac2d04f0-1495-45d1-b1e6-86b976e220ef)

**Comment by JoonghyunCho** [comment]
Can you share the test environment like TV binary info?

**Comment by DIMANRUS** [comment]
> Can you share the test environment like TV binary info?

Samsung Smart Monitor M5 EU. Tizen 6.5. I somehow started once and every other time, but after that the WebView did not open at all. I've tried both nui and xf, elmSharp, it's just a black screen everywhere

**Comment by shyunMin** [comment]
Sorry, I'm late to find the person in charge of `WebView`
It seems that there is an issue in `Webview` regardless of UI F/W. 
Would you please check one more thing whether the NUI App without `Webview` works properly on your target. 
(We don't have Samsung Smart Monitor M5, so we couldn't  reproduce this issue)
If it is confirmed that there is no UI problem, I'll report this issue to the web team.

**Comment by DIMANRUS** [comment]
Only the WebView control has a black screen, but not the application. I think I got you right. I can send a project.

**Comment by DIMANRUS** [comment]
I will also try to reset the monitor to factory settings and create the project again and I will write to you. But I don't have a chance to check on the emulator yet, since Hyper-V is enabled.

**Comment by DIMANRUS** [comment]
I reset the monitor to factory settings. The situation remained the same. I tried Xamarin.Forms (but it was written about it in the documentation that WebView is not supported there at all, but I definitely opened it once before), after I tried NUI with TargetGramework tizen50 and tizen90, WebView with a black screen. After ElmSharp, but the same thing. Everywhere I added the privilege in the manifest (http://tizen.org/privilege/internet ) and tried to open different sites, both http and https.

**Comment by shyunMin** [comment]
Hello, @DIMANRUS 
You don't need to check again on emulator, I just want to check that there's no problem in the other UI Controls such as Label, Button on target(M5). I think that it can be tested using simple application created by template, I'd like to suggest to use NUI template.

**Comment by DIMANRUS** [comment]
> Hello, @DIMANRUS 
> You don't need to check again on emulator, I just want to check that there's no problem in the other UI Controls such as Label, Button on target(M5). I think that it can be tested using simple application created by template, I'd like to suggest to use NUI template.

The problem is only with the WebView, the rest of the elements are displayed and working

**Comment by DIMANRUS** [comment]
I found the reason. If you set the api version 1 or 10 in the manifest for ui-application, then WebView works.
-- NUI App --
https://1drv.ms/v/s!AhxXL2syaMMQluB6zLs6kbJPDeJMYQ?e=HErxrI
---------------

-- Xamarin.Forms App --
https://1drv.ms/v/s!AhxXL2syaMMQluB7Ke8klhkOChQK_Q?e=jZppXf
---------------------------

**Comment by shyunMin** [comment]
Thank you for sharing the result :)
Since the backend of Xamarin.Forms is changed to NUI from Elmsharp, we are recommending to use NUI or MAUI instead of Elmsharp.
And about api-version, please check below TizenFX API documents, the required version of `NUI.BaseComponents.WebView` is 9.
https://samsung.github.io/TizenFX/API9/api/Tizen.NUI.BaseComponents.WebView.html

**Comment by DIMANRUS** [comment]
Thanks for the reply. So Api 9 is Tizen 6.5? And WebView won't work on a lower version of Tizen? Does MAUI only work with Tizen 7.0 and above

**Comment by shyunMin** [comment]
Yes, you can check the platform version mapped to api level here - https://github.com/samsung/tizenfx#branches,
And Tizen supports .NET 6 including MAUI since 7.0.

**Comment by DIMANRUS** [comment]
And in order for me to use weView, which will work on Tizen 4.0 and higher, do I need to use the old project template? If we take Xamarin.Forms
