### ISSUE TITLE
Use GL view with shared thread

### ISSUE THREAD

**Issue by OmidID** [Samsung/Tizen.NET#255]
Hello,

In the example of the NUI, I cannot find if it possible to use GL with a shared thread than the GL thread.

Is it possible to access the GL from another thread?

Thanks.

**Comment by JoonghyunCho** [comment]
@dongsug-song , can you answer for this question?

**Comment by OmidID** [comment]
Hello @JoonghyunCho  @dongsug-song 

Any update here?

**Comment by dongsug-song** [comment]
To : sidein@samsung.com
hello, 
if you don't mind, please check this.
thank you.

**Comment by sparrow74** [comment]
Hello, @OmidID 
 Do you want a example of GLView?
