### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by HavenDV** [Samsung/Tizen.NET#256]
Hello. Since, according to laws and also github rules, repositories without a license can only be viewed, it would be great to include an explicit license.
Link:
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

P.S. I saw the license in the workload folder, and I think the main problem here is with samples, and perhaps it is worth moving the license to the root and marking a separate license for samples

**Comment by JoonghyunCho** [comment]
@HavenDV Thanks for pointing that out.
