### ISSUE TITLE
dotnet workload uninstall tizen does not work on Windows Arm64

### ISSUE THREAD

**Issue by HavenDV** [Samsung/Tizen.NET#258]
I'm developing a [similar workload for the Uno Platform](https://github.com/HavenDV/Uno.Sdk), and I noticed that the installation in the windows script looks like a hack and tries to do the implementation details of this command: `dotnet workload install tizen --skip-manifest-update.` For net 7.0.401 this is most likely missing some details and the `uno workload uninstall tizen` command returns that no such workload was found.
<img width="1163" alt="image" src="https://github.com/Samsung/Tizen.NET/assets/3002068/4709a4d4-b035-4407-98ba-f101fbaa6b8c">

I am also solving this problem and I will share the progress in the future 

P.S. Linux/macos works correctly
I'm guessing this was done to avoid releasing separate tizen MSI nuget packages and it works as is for now anyway, so it's just a note for the future

**Comment by dkson95** [comment]
@HavenDV Hi,

Would you please check

1. https://github.com/Samsung/Tizen.NET/wiki/Installing-Tizen-.NET-Workload
2. https://marketplace.visualstudio.com/items?itemName=tizen.VSToolsTizen2022

```
> dotnet workload list

설치된 워크로드 ID           매니페스트 버전               설치 원본
--------------------------------------------------------------
tizen                 7.0.120/7.0.300        SDK 7.0.300
```
Thank you,
Dongkyun.

**Comment by HavenDV** [comment]
I tried it on another computer and it works correctly for the following configuration (Windows 11 x64 + dotnet 8.0 rc 2).
I discovered this particular problem on Windows 11 Arm64 + dotnet 7.0.401
