### ISSUE TITLE
Setting up Tizen environment Issue

### ISSUE THREAD

**Issue by JoonghyunCho** [Samsung/Tizen.NET#26]
**Describe the bug**
This issue is reported by @jfversluis.
[log.txt](https://github.com/Samsung/Tizen.NET/files/3420201/log.txt)

> I am setting up a new laptop and trying to setup Tizen again, but I fail and I can’t see why. I think I have all prerequisites, but it still fails to run.
In VS Code it’s stuck on
![image](https://user-images.githubusercontent.com/14328614/61682579-2c5ead00-ad4d-11e9-86b5-ba7d120eb89a.png)
And when I try to run Tizen Studio I set a folder for the workspace but then it crashes. The log is attached.

**Comment by JoonghyunCho** [comment]
@(sec)manish-r
This could be due to Improper JDK Installation as from the logs it can be see as the classes are not found.
Request to refer to https://developer.tizen.org/ko/development/articles/openjdk-10-and-openjfx-installation-guide?langredirect=1 guide for installation of JDK 10 on Mac.

Note:
- The OpenJDK (Java 10)  and OracleJDK (Java 8) version is very important because tizen sdk doesn't support latest Java version yet.
- Make sure to install the OpenJFX after installing OpenJDK

**Comment by JoonghyunCho** [comment]
@jfversluis, I was told that the lastest VS Code release was before OpenJDK support...so I have raised an issue a few days ago. Sorry for the issue.

**Comment by jfversluis** [comment]
No problem! I just got another email that looks promising as well, so I will check that out too :)

**Comment by JoonghyunCho** [comment]
@jfversluis, I thought now you have a problem with connection between VS Code and Tizen environment in OpenJDK base. Are also you unable to start Tizen tools like Package Manager, Emulator Manager and etc?

**Comment by jfversluis** [comment]
As it turns out I am able to start the Package Manager and Tizen Studio etc. so yes, it just seems to be the connection between Tizen and VS Code for now.

**Comment by winstone77** [comment]
@jfversluis, 
It seems that the install java version is 12.0.1. 
Sorry, current Tizen Studio and VS Code  are not able to support this java version.
We have a plan to support this java version by end of October. 
Thus, Could you install recommended Java version (Oracle JDK8 or OpenJDK 10)?

**Comment by JoonghyunCho** [comment]
@jfversluis , Yes, like I mentioned on the earlier comment, it seems VS Code is not recognizing the OpenJDK environment.
And you would be OK with VS for Mac extension for Tizen? Have you tried?

**Comment by jfversluis** [comment]
@winstone77 I think I tried that, but I probably did something wrong :)

@JoonghyunCho I would definitely be OK with that! I tried it and it seems to work, didn't run an actual Tizen app yet, but all other things seem to work. I could install the emulator and run the package manager etc. so I will check that out for now.

**Comment by JoonghyunCho** [comment]
@jfversluis , and for VS Code, I was told that there is no plan to release the next version of Tizen extension at the moment. Therefore, the solution for this original issue at the moment is using jdk 8 version (not OpenJDK 10 version).
