### ISSUE TITLE
Tizen SDK 5.5. Question.

### ISSUE THREAD

**Issue by DIMANRUS** [Samsung/Tizen.NET#260]
Hello. Tizen SDK 5.5 was shown at SDC 2023. Samsung TV emulator with WHPX. Where is this SDK actually? Still in development?

**Comment by dkson95** [comment]
@DIMANRUS Hello

We are now preparing the Tizen SDK 5.5 release (along with features including `WHPX` based on `tizen` profile) and It is planned to be opened at the end of this month after internal testing.

Thank you!

**Comment by DIMANRUS** [comment]
Ok. Thank you. I'll be waiting.
