### ISSUE TITLE
Workload creates wrong manifest for dll with a hyphen in it.

### ISSUE THREAD

**Issue by HJLeee** [Samsung/Tizen.NET#264]
Please refer the following for reproduction.

```
· ~/tmp/tizen-workload $ dotnet new tizen -n tizen-workload
The template "Tizen .NET Application" was created successfully.

· ~/tmp/tizen-workload $ cd tizen-workload/
· ~/tmp/tizen-workload/tizen-workload $ ls
Main.cs  shared  tizen-manifest.xml  tizen-workload.csproj

· ~/tmp/tizen-workload/tizen-workload $ dotnet build
MSBuild version 17.4.8+6918b863a for .NET
  Determining projects to restore...
  Restored /home/leee/tmp/tizen-workload/tizen-workload/tizen-workload.csproj (in 68 ms).
  tizen-workload -> /home/leee/tmp/tizen-workload/tizen-workload/bin/Debug/net7.0-tizen/tizen-workload.dll
  tizen-workload is signed with Default Certificates!

tizen-manifest.xml : error TS0002: The 'tizen_workload.dll' file was not found. [/home/leee/tmp/tizen-workload/tizen-workload/tizen-workload.csproj]
tizen-manifest.xml : error TS0002: Please check the exec attribute of tizen-manifest.xml or check the assembly name [/home/leee/tmp/tizen-workload/tizen-workload/tizen-workload.csproj]

Build FAILED.

tizen-manifest.xml : error TS0002: The 'tizen_workload.dll' file was not found. [/home/leee/tmp/tizen-workload/tizen-workload/tizen-workload.csproj]
tizen-manifest.xml : error TS0002: Please check the exec attribute of tizen-manifest.xml or check the assembly name [/home/leee/tmp/tizen-workload/tizen-workload/tizen-workload.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.51

· ~/tmp/tizen-workload/tizen-workload $ ls bin/Debug/net7.0-tizen/
publish  tizen-workload.deps.json  tizen-workload.dll  tizen-workload.pdb  tizen-workload.runtimeconfig.json  tpkroot

· ~/tmp/tizen-workload/tizen-workload $ cat tizen-manifest.xml 
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns="http://tizen.org/ns/packages" api-version="7" package="com.companyname.tizen_workload" version="1.0.0">
  <profile name="common" />
  <ui-application appid="com.companyname.tizen_workload"
          exec="tizen_workload.dll"
          type="dotnet"
          multiple="false"
          taskmanage="true"
          nodisplay="false"
          launch_mode="single">
    <label>tizen_workload</label>
    <icon>tizen_workload.png</icon>
    <metadata key="http://tizen.org/metadata/prefer_dotnet_aot" value="true" />
  </ui-application>
</manifest>

```

**Comment by rookiejava** [comment]
good catch! Seems like this issue stems from the [Safe Naminf Rule](https://github.com/dotnet/templating/wiki/Naming-and-default-value-forms) of dotnet templating. 

<html>
<body>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">E.g, if user use<span> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; white-space: break-spaces; background-color: var(--bgColor-neutral-muted, var(--color-neutral-muted)); border-radius: 6px;">My-App</code><span> </span>as the name, the generated content will be as follows:</p>

Form | Source | Transformed value
-- | -- | --
identity | My-App | My-App
namespace | My-App | My_App
class name | My-App | My_App
lower case namespace | My-App | my_app
lower case class name | My-App | my_app


</body>
</html>

However, the `tizen-manifest.xml` file doesn't recognize the names converted according to this rule. 

@sung-su, @JoonghyunCho could you check and make sure the `tizen-manifest.xml` file aligns with the transformed names when it genereted?

**Comment by JoonghyunCho** [comment]
Here are the options I can think of right now to fix the issue:
1. Keep the user specified name, `tizen-workload`, for `exec` value.
  : Looks most preferred, but not simple. More investigation is required for conditional template generation.
2. Add `<AssemblyName>TizenApp1</AssemblyName>` property in `TizenApp1.csproj` to make the name of dll fit to the naming rule.
  : Easy to apply, but then it is Tizen specific. Not sure if there could be the side effects.

Let me more think about the solution.
