### ISSUE TITLE
Can not launch Tizen Samsung TV on Macbook M1

### ISSUE THREAD

**Issue by vankhoa01** [Samsung/Tizen.NET#265]
I got this issue when I try to run Samsung TV on Macbook M1 device:
<img width="655" alt="Screenshot 2023-11-02 at 1 44 08 PM" src="https://github.com/Samsung/Tizen.NET/assets/8953129/b5901a10-d968-4bb3-ad3b-05ff5a9aa882">

Looks like Macbook M1 didn't support Intel VT-X anymore https://discussions.apple.com/thread/253021057
So I can not install HAXM like documentation here https://developer.tizen.org/development/tizen-studio/download/installing-tizen-studio/hardware-accelerated-execution-manager
Is there any solution to launch Samsung TV on M1 now ?
Thank you so much

**Comment by sangwook96** [comment]
Hi,
I am happy to write something to you
Currently, Tizen emulator is not working on the M1 chip like M2
Actually, we have no plan to support it now. Just, I can tell you our situation as it is.
Sorry for saying bad news to you. If there is any news, we will update it again.

**Comment by vankhoa01** [comment]
@sangwook96 : Yeah, I see 
Thank you for your reply

**Comment by dkson95** [comment]
no plan to support for now.
