### ISSUE TITLE
GamePad and Tizen.TV cannot found

### ISSUE THREAD

**Issue by OmidID** [Samsung/Tizen.NET#269]
Hello, 

After I watched the Samsung conference I could not find anything related to GamePad in Tizen API.
https://www.samsungdeveloperconference.com/sessions/gamepad-on-tizen-tv

By the way, the emulator cannot detect the gamepad I connected. any solution?

Thanks,
Omid

**Comment by OmidID** [comment]
?

**Comment by sung-su** [comment]
I apologize for the late response.
We were unable to find an answer to your question.
How about asking a question to https://developer.samsung.com/dev-support ?
