### ISSUE TITLE
TV Emulator Preparing

### ISSUE THREAD

**Issue by DIMANRUS** [Samsung/Tizen.NET#270]
Hello.  I have launched TV Emulator 7 on WSL 2. It started, but when I press the home button, this inscription is always shown, and I can't launch any application. Only volume switching works.
![image](https://github.com/Samsung/Tizen.NET/assets/41239551/7785a48c-329d-41ea-9f14-8d41b0521e12)

**Comment by gengjingjing2011** [comment]
We provide the windows version of the emulator, why do not you run it on windows?

**Comment by gengjingjing2011** [comment]
Emulator is support with hyper-v
can you check the Emulator Requirements on https://docs.tizen.org/application/tizen-studio/setup/prerequisites/?

**Comment by DIMANRUS** [comment]
> Emulator is support with hyper-v can you check the Emulator Requirements on https://docs.tizen.org/application/tizen-studio/setup/prerequisites/?

I'm only talking about TV https://github.com/Samsung/Tizen.NET/issues/233#issuecomment-1452998699 .

**Comment by gengjingjing2011** [comment]
I am sorry. 
TV Emulator is not support WHPX now. 
we plan to support it in next version.

**Comment by DIMANRUS** [comment]
> I am sorry. 
> TV Emulator is not support WHPX now. 
> we plan to support it in next version.

This wsl2 with kvm, not whpx. Emulator run, i can change volume, but when click home button -> preparing

**Comment by gengjingjing2011** [comment]
can you share us the reproduction steps and the logs?
C:\tizen-studio-data\emulator\vms\T-samsung-8.0-x86\logs\emulator.klog
C:\tizen-studio-data\emulator\vms\T-samsung-8.0-x86\logs\emulator.log
Thank you!

**Comment by DIMANRUS** [comment]
[emulator.klog.log](https://github.com/Samsung/Tizen.NET/files/14122127/emulator.klog.log)
[emulator.log](https://github.com/Samsung/Tizen.NET/files/14122128/emulator.log)
I couldn't reinstall 7.0, 8.0 appeared there, but now it doesn't run at all)

> can you share us the reproduction steps and the logs? C:\tizen-studio-data\emulator\vms\T-samsung-8.0-x86\logs\emulator.klog C:\tizen-studio-data\emulator\vms\T-samsung-8.0-x86\logs\emulator.log Thank you!

**Comment by gengjingjing2011** [comment]
I am sorry to tell you that Emulator cannot run inside WSL2 container because it cannot be virtualized twice.
