### ISSUE TITLE
Tizen TV 8.0 Emulator not run.

### ISSUE THREAD

**Issue by DIMANRUS** [Samsung/Tizen.NET#271]
Hello. I installed Samsung Tv Emulator 8 from the website, but it freezes on startup and that's it. Why is there an eternal problem with Samsung TV emulators?
![image](https://github.com/Samsung/Tizen.NET/assets/41239551/1b94447f-230a-464d-9116-cec5b4c0f16a)

**Comment by gengjingjing2011** [comment]
can you share us the PC Computer configuration and operating environment？

**Comment by DIMANRUS** [comment]
PC configuration
![image](https://github.com/Samsung/Tizen.NET/assets/41239551/c920ef71-1f72-4cfc-bc14-23f1cd69572b)

**Comment by gengjingjing2011** [comment]
can you share us the reproduction steps and the logs?
C:\tizen-studio-data\emulator\vms\T-samsung-8.0-x86\logs\emulator.klog
C:\tizen-studio-data\emulator\vms\T-samsung-8.0-x86\logs\emulator.log
 Thank you!

**Comment by DIMANRUS** [comment]
> can you share us the reproduction steps and the logs? C:\tizen-studio-data\emulator\vms\T-samsung-8.0-x86\logs\emulator.klog C:\tizen-studio-data\emulator\vms\T-samsung-8.0-x86\logs\emulator.log Thank you!

[emulator.log](https://github.com/Samsung/Tizen.NET/files/14108805/emulator.log)
[emulator-klog.log](https://github.com/Samsung/Tizen.NET/files/14108810/emulator-klog.log)

**Comment by gengjingjing2011** [comment]
Some windows system  may get his issue.. please add following entry in vmconfig file. （C:\tizen-studio-data\emulator\vms\T-samsung-8.0-x86\vm_launch.conf）
-accel whpx,kernel-irqchip=off
Please refer: https://gitlab.com/qemu-project/qemu/-/issues/346
try it please！

**Comment by gengjingjing2011** [comment]
Please check the configuration ：
https://developer.tizen.org/development/tizen-studio/download/installing-tizen-studio/hardware-accelerated-execution-manager
![Emulator](https://github.com/Samsung/Tizen.NET/assets/40655964/845963cc-f48d-42a8-930d-ebb971030d36)
if the configuration is right ,the "CPU VT" and "GPU" are all "ON" the Emulator Configuration.

**Comment by DIMANRUS** [comment]
> Please check the configuration ：
> https://developer.tizen.org/development/tizen-studio/download/installing-tizen-studio/hardware-accelerated-execution-manager
> ![Emulator](https://github.com/Samsung/Tizen.NET/assets/40655964/845963cc-f48d-42a8-930d-ebb971030d36)
> if the configuration is right ,the "CPU VT" and "GPU" are all "ON" the Emulator Configuration.

I can't disable Hyper-V, I need it. And in the configuration, everything is on

**Comment by gengjingjing2011** [comment]
I am sorry.
TV Emulator is not support WHPX now.
we plan to support it in next version.

**Comment by DIMANRUS** [comment]
> I am sorry. TV Emulator is not support WHPX now. we plan to support it in next version.

Ok. Thanks
