### ISSUE TITLE
.NET 8 compability with Tizen TV Emulator

### ISSUE THREAD

**Issue by confect1on** [Samsung/Tizen.NET#276]
I've been developing an application for Tizen TV using MAUI framework. As far as I see the Tizen TV extension is supported by only .NET 6 even in the last release(https://developer.samsung.com/smarttv/develop/tools/tv-extension/download.html)
Is it correct that I'm not able to develop and test applications using higher version than .NET 6 for Tizen TV?

**Comment by confect1on** [comment]
It can be repeat of https://github.com/Samsung/Tizen.NET/issues/273. If so, please close it. I've created a new issue because I've tried deploying only an application on .NET 7, not .NET 8

**Comment by rookiejava** [comment]
Sorry for late resposne. As you might know, Tizen TV officailly supports only .NET 6 as of now. Unfortunately, higer versions of .NET (.NET7, .NET8, .NET 9) are not yet supported. It would be best to wait for Tizen TV offical announcement regarding updated support for lastet .NET version.

**Comment by confect1on** [comment]
Thanks for the response!
