### ISSUE TITLE
Workload installation fails, cannot compile MAUI projects

### ISSUE THREAD

**Issue by TAMHAN** [Samsung/Tizen.NET#277]
Dear Friends, please allow me to report a weird happening on my Windows 11 workstation. For a newspaper article, I had to reinstall the Tizen workload. I get the following errors:
PS C:\Users\tamha> dotnet workload install tizen

Das Werbemanifest wurde nicht aktualisiert. Das Manifestpaket für samsung.net.sdk.tizen ist nicht vorhanden.
Downloading Samsung.Tizen.Sdk.Msi.x64 (8.0.138)
Fehler bei der Workloadinstallation. Für die installierten Pakete wird ein Rollback ausgeführt...
Fehler bei der Workloadinstallation: One or more errors occurred. ("Version "8.0.138" des Pakets "samsung.tizen.sdk.msi.x64"" wurde in NuGet-Feeds "https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" nicht gefunden.)
PS C:\Users\tamha> dotnet workload install tizen  --include-previews

Das Werbemanifest wurde nicht aktualisiert. Das Manifestpaket für samsung.net.sdk.tizen ist nicht vorhanden.
Downloading Samsung.Tizen.Sdk.Msi.x64 (8.0.138)
Fehler bei der Workloadinstallation. Für die installierten Pakete wird ein Rollback ausgeführt...
Fehler bei der Workloadinstallation: One or more errors occurred. ("Version "8.0.138" des Pakets "samsung.tizen.sdk.msi.x64"" wurde in NuGet-Feeds "https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" nicht gefunden.)
PS C:\Users\tamha> dotnet workload install tizen  --include-previews --skip-manifest-update

Downloading Samsung.Tizen.Sdk.Msi.x64 (8.0.138)
Fehler bei der Workloadinstallation. Für die installierten Pakete wird ein Rollback ausgeführt...
Fehler bei der Workloadinstallation: One or more errors occurred. ("Version "8.0.138" des Pakets "samsung.tizen.sdk.msi.x64"" wurde in NuGet-Feeds "https://api.nuget.org/v3/index.json;C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" nicht gefunden.)
PS C:\Users\tamha>

The dotnet info yields the following:
PS C:\Users\tamha> dotnet --info
.NET SDK:
 Version:           8.0.300-preview.24203.14
 Commit:            b7e38f457d
 Workload version:  8.0.300-manifests.72a3b485
 MSBuild version:   17.10.0+4f6b1bb28

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300-preview.24203.14\

Installierte .NET-Workloads:
 [android]
   Installationsquelle: SDK 8.0.300-preview.24203, VS 17.9.34728.123, VS 17.10.34818.151
   Manifestversion:    34.0.95/8.0.100
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.95\WorkloadManifest.json
   Installationstyp:        FileBased

 [aspire]
   Installationsquelle: SDK 8.0.300-preview.24203, VS 17.10.34818.151
   Manifestversion:    8.0.0-preview.6.24214.1/8.0.100
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0-preview.6.24214.1\WorkloadManifest.json
   Installationstyp:        FileBased

 [ios]
   Installationsquelle: SDK 8.0.300-preview.24203, VS 17.9.34728.123, VS 17.10.34818.151
   Manifestversion:    17.2.8053/8.0.100
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8053\WorkloadManifest.json
   Installationstyp:        FileBased

 [maccatalyst]
   Installationsquelle: SDK 8.0.300-preview.24203, VS 17.9.34728.123, VS 17.10.34818.151
   Manifestversion:    17.2.8053/8.0.100
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8053\WorkloadManifest.json
   Installationstyp:        FileBased

 [maui-windows]
   Installationsquelle: SDK 8.0.300-preview.24203, VS 17.9.34728.123, VS 17.10.34818.151
   Manifestversion:    8.0.7/8.0.100
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.7\WorkloadManifest.json
   Installationstyp:        FileBased

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  3.0.103 [C:\Program Files\dotnet\sdk]
  6.0.111 [C:\Program Files\dotnet\sdk]
  6.0.421 [C:\Program Files\dotnet\sdk]
  8.0.204 [C:\Program Files\dotnet\sdk]
  8.0.300-preview.24203.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
PS C:\Users\tamha>

I have also already tried to restrict with global.json to a version 6 of the SDK, and it also does not work.

**Comment by TAMHAN** [comment]
Hello,

thank you. Sadly, I still was not able to solve this issue.


Tam

With best regards
Tam HANNA

--
Enjoy electronics, 3D printing and cigars? Join more than 21000 followers on my Instagram athttp://www.instagram.com/tam.hanna

**Comment by sung-su** [comment]
@TAMHAN 
I apologize for the delayed response.
Unfortunately, unlike other platforms, Tizen workload installation is a different due to provider differences.
You can install an [VS extension](https://marketplace.visualstudio.com/items?itemName=tizen.VisualStudioToolsforTizen) or use a [script](https://github.com/Samsung/Tizen.NET/blob/main/workload/scripts/workload-install.ps1).
Thank you.

**Comment by sung-su** [comment]
That 404 error seems a weird.
Please try again after [this](https://github.com/Samsung/Tizen.NET/wiki/Trouble-Shooting#uninstall-tizen-workload).

```
PS C:\Users\sung-su.kim> dotnet --version
8.0.300

PS C:\Users\sung-su.kim> dotnet --list-sdks
3.1.426 [C:\Program Files\dotnet\sdk]
6.0.404 [C:\Program Files\dotnet\sdk]
7.0.102 [C:\Program Files\dotnet\sdk]
8.0.101 [C:\Program Files\dotnet\sdk]
8.0.300 [C:\Program Files\dotnet\sdk]

PS C:\Users\sung-su.kim> dotnet workload list

설치된 워크로드 ID      매니페스트 버전             설치 원본
-------------------------------------------------
tizen            8.0.149/8.0.300      SDK 8.0.300

`dotnet workload search`을 사용하여 설치할 추가 워크로드를 찾습니다.

PS C:\Users\sung-su.kim>
```
