### ISSUE TITLE
When creating a web project, the files of the entire project are deleted

### ISSUE THREAD

**Issue by DIMANRUS** [Samsung/Tizen.NET#279]
Hello. If you add a tizen web project in Visual Studio to an existing project, you get an error and all the files of the entire solution simply disappear and are nowhere else. I once lost some changes and had to do everything again.

**!!!!_And why aren't there any answers, Github just closes the issue and that's it. Extremely unpleasant. I hope it will be more pleasant to work with Avalonia Tizen._**

**Comment by shyunMin** [comment]
Sorry for late. It seems to be a problem with VS tizen extension tool. 
I've sent this issue to SDK team and I'll reply as soon as they check.

**Comment by shyunMin** [comment]
Hello, I've received a reply from SDK team today. They said this issue will be resolved in next release and next release is scheduled in October. Sorry I'm too late.
