### ISSUE TITLE
Tizen 6.0

### ISSUE THREAD

**Issue by DapperMickie** [Samsung/Tizen.NET#280]
Is there any way I can create a .NET MAUI app for Tizen 6.0?
Or any other way to develop .NET apps for Tizen 6.0? 
I want to make an app for the Kick livestreaming platform.

**Comment by sung-su** [comment]
Unfortunately, we support `.NET6` and `.NET MAUI` from `Tizen 7.0`.

**Comment by sung-su** [comment]
We have been supporting `.NET` framework since `Tizen 4.0`, so of course, you can run C# projects on `Tizen 6.0`.
However, `.NET MAUI` works on `.NET6` or higher version and we support `.NET6` from `Tizen 7.0`.
Is there a reason why it should be `Tizen 6.0` ?

**Comment by DapperMickie** [comment]
Well my TV runs on 6.0 and I wanted to make the app work with my TV.

**Comment by sung-su** [comment]
Currently, there is no support plan for `Tizen 6.0`.
