### ISSUE TITLE
Build error with NUIGadgetManager.Unload API

### ISSUE THREAD

**Issue by namsuha** [Samsung/Tizen.NET#282]
Hello
I modified as below to use NUIGadgetManager.Unload API.
( net6.0-tizen9.0, Tizen.NetAPI12)
build is ok in visual studio. but, Build error occurs with vbs build
How do I modify to use it?

- -- project file --
     &lt; TargetFramework &gt; net6.0-tizen9.0 &lt; /TargetFramework &gt;
      **&lt;PackageReference Include="Tizen.NET.API12" Version="12.0.0.*" /&gt;** 

**-- vbs build error --**
/usr/share/dotnet-build-tools/sdk/sdk/6.0.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(216,5): error NETSDK1140: 9.0 is not a valid TargetPlatformVersion for tizen. Valid versions include: [/home/abuild/rpmbuild/BUILD/com.samsung.tv.quicklaunch-2.5.9991/QuickLaunch/QuickLaunch.csproj]
/usr/share/dotnet-build-tools/sdk/sdk/6.0.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(216,5): error NETSDK1140: 6.5 [/home/abuild/rpmbuild/BUILD/com.samsung.tv.quicklaunch-2.5.9991/QuickLaunch/QuickLaunch.csproj]
/usr/share/dotnet-build-tools/sdk/sdk/6.0.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(216,5): error NETSDK1140: 7.0 [/home/abuild/rpmbuild/BUILD/com.samsung.tv.quicklaunch-2.5.9991/QuickLaunch/QuickLaunch.csproj]
/usr/share/dotnet-build-tools/sdk/sdk/6.0.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(216,5): error NETSDK1140: 8.0 [/home/abuild/rpmbuild/BUILD/com.samsung.tv.quicklaunch-2.5.9991/QuickLaunch/QuickLaunch.csproj]

--- Base repo : http://repos.vd.sec.samsung.net/base/tizen-9.0-base/standard/tizen-9.0-base-standard_20240805.1/

**Comment by JoonghyunCho** [comment]
Hello, Looks like vbs needs to update Tizen workload to the latest. We will try figuring how to update.

**Comment by namsuha** [comment]
Thank you for your reply.
Could you let me know when can I use it?

**Comment by JoonghyunCho** [comment]
Updating build-tools package to use the latest Tizen Workload.

**Comment by JoonghyunCho** [comment]
It gets little delayed to update `build-tools`  for vbs

**Comment by namsuha** [comment]
Ok, I'll wait

**Comment by JoonghyunCho** [comment]
Please try now :)
