### ISSUE TITLE
.NET Development is not supproted on the connected device model

### ISSUE THREAD

**Issue by cangunaydin** [Samsung/Tizen.NET#283]
pushed org.tizen.example.Test1.Common-1.0.0.tpk	  0%	      0KB	    0KB/s
	pushed org.tizen.example.Test1.Common-1.0.0.tpk	 42%	   2496KB	    0KB/s
	pushed org.tizen.example.Test1.Common-1.0.0.tpk	100%	   5813KB	    0KB/s
	1 file(s) pushed. 0 file(s) skipped.
	C:\Development\Tizen-Net\Test1\Test1\Test1.Common\bin\Debug\tizen10.0\org.tizen.example.Test1.Common-1.0.0.tpk   6852KB/s (5952987 bytes in 0.848s)
	#############################################################################################
	###############.NET Development is not supproted on the connected device model###############
	#############################################################################################

Hello i am trying to deploy a basic app from visual studio to my device see if it is working.
Smart signage tv that i use is QM32C (tv7.0)
![image](https://github.com/user-attachments/assets/6b3a6320-2e74-4dbc-bae2-121afc9357ae)
When i try to deploy basic TizenCrossNet
![image](https://github.com/user-attachments/assets/f6e67cf1-88c2-42f9-80ef-115388de8254)

 or 
![image](https://github.com/user-attachments/assets/e46a1cc9-7e4d-47b4-a6c6-076ad893b80b)

i am getting error: .NET Development is not supproted on the connected device model
according to docs both nui and TizenCrossNet is supported for tizen7.0. 

Am i missing sth over here? What could be the reason that i can not deploy .net app?
Also when i look at the capabilities from sdb command.
![image](https://github.com/user-attachments/assets/cbfe3cc4-c05d-4cf7-a880-a2ad97506cdc)
it seems dotnet core debugging is there.

**Comment by sung-su** [comment]
I apologize for my delayed response.
Policies may differ depending on the device.
How about inquiring below?
https://developer.samsung.com/dev-support
