### ISSUE TITLE
Not able to install the tizen workload for dotnet version 8.0.401.

### ISSUE THREAD

**Issue by anandhan-rajagopal** [Samsung/Tizen.NET#284]
While trying to install the tizen workload using the following command:

curl -sSL https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.sh | sudo bash

Getting the following error:
Check Tizen Workload for sdk 8.0.401.
Installing samsung.net.sdk.tizen.manifest-8.0.400/8.0.400 to /usr/local/share/dotnet/sdk-manifests/8.0.400...
[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.QiuE3XDekk/manifest.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.QiuE3XDekk/manifest.zip or
        /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.QiuE3XDekk/manifest.zip.zip, and cannot find /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.QiuE3XDekk/manifest.zip.ZIP, period.
No such files to install.
DONE

**Comment by anandhan-rajagopal** [comment]
@JoonghyunCho Could you have any Idea to resolve this?

**Comment by JoonghyunCho** [comment]
Hello, it may be your environment is behind proxy?
Please check your proxy setup or try manually downloading a script and giving "-x [proxy]" option at https://github.com/Samsung/Tizen.NET/blob/558b1faa8c2e605ce2c15fb914bad1bb1614305c/workload/scripts/workload-install.sh#L210
