### ISSUE TITLE
Tizen .Net app on Samsung Smart TV

### ISSUE THREAD

**Issue by alvicald** [Samsung/Tizen.NET#286]
I read all tutorials about creating the Tizen .Net Application for Samsung Smart TV and still don't understand how to install my building application to Samsung Smart TV via Tizen Studio as it can do with  .wgt files. Just take  the  .tpk file created by building the application, somehow to add  this file to Tizen Studio, find that file as application in APPS on Samsung Smart TV and to install that on Tv. Is it possible to do?

**Comment by sung-su** [comment]
How about referring to the link below?
https://developer.samsung.com/smarttv/develop/tizen-net-tv/getting-started/creating-net-tv-applications.html#Deploying-and-Running-the-Application
