### ISSUE TITLE
Cannot install Tizen SDK on Visual Studio 2019

### ISSUE THREAD

**Issue by xbldx** [Samsung/Tizen.NET#30]
For using a Tizen on Visual Studio 2019, users should install Tizen SDK.

But when I click a "Install new Tizen SDK" button in following window,
![image](https://user-images.githubusercontent.com/31120300/62188182-9a871d80-b3a6-11e9-9e54-2c882ac410d5.png)

a following error is occured and Tizen SDK is not installed.
> [NSIS Error]
Installer integrity check has failed. Common causes include incomplete download and damaged media. Contact the installer's author to obtain a new copy.
![image](https://user-images.githubusercontent.com/31120300/62188272-d28e6080-b3a6-11e9-83d7-80fdebc5496f.png)

- Win 64 bit
- Visual Studio 2019

**Comment by JoonghyunCho** [comment]
Fixed on 29-Jul-2019.
The installer for Windows 64 has been broken for a few days, but now it is re-uploaded.
Please try again.
