### ISSUE TITLE
Can help us update Visual Studio Tools for Tizen in Visual Studio 2019

### ISSUE THREAD

**Issue by dangvonhatquang59qtdllh** [Samsung/Tizen.NET#4]
Dear Developer Tizen Team,
Can help us update Visual Studio Tools For Tizen with Visual Studio version 2019 in Visual Studio Extension Marketplace.
Thank Team!

**Comment by rookiejava** [comment]
We have internally prepared support for VS2019 and are in the process of validating it for public release. I will notify you when it is completed. Thank you for your interest. :)

**Comment by rookiejava** [comment]
Visual Studio Toos for Tizen is now available on Visual Studio 2019. You can install it from your Visual Studio  2019 as below.

1. Go to `Extensions` and choose `Manage Extenstions`
2. Search `Tizen`
3. Install the `Visual Studio Tools for Tizen` (version 2.5.0.0 or higher)

![vstizen_2019](https://user-images.githubusercontent.com/1029134/56941244-432aa480-6b4e-11e9-931c-3efc9945fe1e.png)
