### ISSUE TITLE
Error popup when launching Wearable Emulator

### ISSUE THREAD

**Issue by thanhlv93** [Samsung/Tizen.NET#44]
**Describe the bug**
After installed
Samsung Wearable Extension : 1.4.1
Samsung Certificate Extension  : 2.0.41
I start wearable emulator I got  an error : 

![Screenshot from 2019-12-03 15-40-29](https://user-images.githubusercontent.com/5988002/70034155-52da0200-15e3-11ea-930b-f40582465463.png)

**To Reproduce**
1. Go to 'Install Samsung Wearable Extension v1.4.1 and Samsung Certificate Extension v2.0.41'
2. Click on 'Create new wearable 4.0'

**Expected behavior**
Install extension to connect from real android phone to emulator wearable.

**Screenshots**

**Environment (please complete the following information):**
 - Ubuntu 16.04
 - Tizen Platform Version 4.0

**Comment by JoonghyunCho** [comment]
Hello @thanhlv93 ! 
I reported your issue and got the following steps to resolve the issue.
Please try the below steps to see if it resolves your issue,

  1. Run the package manager and remove the `Samsung Wearable Extension` under Extension SDK tab.
  2. Check the below directory. (It should not exist ! because you have removed it)
      tizen-studio/platforms/tizen-4.0/wearable/emulator-images/add-ons/sap
  3. Install Wearable Extension again using Package manager
  4. Run the emulator manager
  5. Delete the emulator you have created and create a new one.

**Comment by suntzu195** [comment]
@JoonghyunCho  Thanks for your answer but I it's still error with wearable os 4.0 . I installed extension and connected to real phone with wearable os 3.0 .

**Comment by thanhlv93** [comment]
@JoonghyunCho Thanks for your answer but I it's still error with wearable os 4.0 . I installed extension and connected to real phone with wearable os 3.0 .

**Comment by JoonghyunCho** [comment]
@thanhlv93 @suntzu195, and just so you know, this error only affects to SAP feature. You can still use all other features on emulator.
oh ok, I will ask again. What exactly do you mean by that you connected to real phone with wearable os 3.0 ?

**Comment by thanhlv93** [comment]
it's I can test my application with wearable os 3.0 after connected.

**Comment by JoonghyunCho** [comment]
@thanhlv93 oh ok that's cool :) I will update about the error soon.

**Comment by EmilAlipiev** [comment]
I have created exactly same issue here https://github.com/Samsung/Tizen.NET/issues/54
He means that it works on real device. yes for me it works on Galaxy device also but never on emulator. I followed those steps above but it didnt solve the problem.
