### ISSUE TITLE
Visual Studio 2019 hangs on first install in debug mode on Wearable

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.NET#53]
I am not sure if that is related VS or Tizen but when you create a new app and try to debug on VS 2019, It hangs VS 2019 and newer releases. I have to always kill the process.
But when I choose 1st Start without debugging, it installs fine into my galaxy watch and later I can choose debug without any issue. 
So problem is only with first debugging.

**Comment by JoonghyunCho** [comment]
@sangwook96-lee, @winstone77, Please take a look at this issue.

**Comment by EmilAlipiev** [comment]
Just to make it clear it only occurs for debugging device not emulator.

**Comment by YoupHulsebos** [comment]
I have this issues as wel. It has to do with certificates not being right. When I setup certificates on the command line everything works. I'm not able to debug this way though.

You can check if this is true for you can cancalling the debug session and reading the debug log.

**Comment by EmilAlipiev** [comment]
this seems to be fixed in the latest updates of VS2019 or Tizen tools. I dont experience this issue anymore.
