### ISSUE TITLE
How to override default keyboard layout in Galaxy Watch?

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.NET#57]
when i use numeric keyboard on entry and if my language is German, it should display comma instead of dot as comma separator. But when entry is opened, it displays always dot. This is a known issue for Samsung phones also. I am able to override the default keyboard in android like below.
how can i achieve this in Tizen watch?

```
   this.Control.KeyListener = Android.Text.Method.DigitsKeyListener.GetInstance(string.Format("1234567890{0}", Settings.CurrentCultureInfo.NumberFormat.CurrencyDecimalSeparator));
            this.Control.InputType = Android.Text.InputTypes.ClassNumber | Android.Text.InputTypes.NumberFlagDecimal;
```

**Comment by JoonghyunCho** [comment]
@Inhong Hello, can you help with this question? Thanks.
