### ISSUE TITLE
Enhancement Request for Tizen.net

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.NET#58]
Hi,

I have been working with Tizen.net using VS 2019 windows (always up to date latest version.) for 3 months and I really love tizen and would like to participate more. Therefore I decided to summarize my experience and wishes if you consider.
I worked mostly Watch application using a companion with SAP.
 - Accessory sdk wasnt available for .net. therefore I had to create binding library. Your samples are also only in Java. I had to convert java into c#. it was somehow tricky but achieved at the end. Anyone needs a nuget package to use Accessory sdk for tizen.net can download here. https://www.nuget.org/packages/SamsungAccessorySDK.Net/
- for sample c# code; https://github.com/EmilAlipiev/SamsungWearCompanion
  this is use SaAgent but I will update it late with SaAgent2 as well. I am thinking to create a nuget package for those as well. 
This was the fun part now my Android companion app runs perfectly using that code. 

**And the Pain part of the the development**
- I had no possibility to work with emulator.  because of this problem https://github.com/Samsung/Tizen.NET/issues/54
- Debugging experience on Galaxy watch active is also not fluent. Often Sdb.exe is stopping and debugging is broken. 
- Debugging shows that running but app is not launched on the device. This case is persistent and it isnt solved until i restarted the watch. I dont know why this is happening because after sometime, debugging is getting broken on the watch. I am not sure if some memory is getting full or sdb is getting broken but restarting watch fixes the issue. no other way. 
- 80% debugging is useless. Because observing/watching values is not displayed when i hover the mouse on the values on breakpoints, it doesnt show anything.
- When you make a change on xaml and start debugging, it wont update changes. You need to rebuild and start debugging very often.
- When something is not working, for example launching isnt even successful, you wont see any debugging crash but simply app is not launched on the watch. Only way to find out the problem is to check logs. Filter doesnt work on the device logs. I think that you have very bad search function. it needs to be exact keyword with case sensitive. If i search "launch", it doesnt find any log, but if i search "DOTNET_LAUNCH" it finds it. Found logs are also impossible to read because you show only part of it, not all. Only way to find out, everytime to export to txt file and open with text editor and search. How cumbersome is it! 
- I really wish that you work closely with xamarin team and make hotreload working on Tizen. this will be amazing improvement. So painful to do design on Galaxy watch with this function. 
I hope that we can get better updates in the future :) 

Best Regards,
Emil

**Comment by JoonghyunCho** [comment]
@EmilAlipiev 
Thank you very much for sharing your experiences and suggestions! and sorry for your inconvenience at the same time.

I have recognized the problem about using SAP on emulator, and I see it keeps bothering developers. I will definitely make sure this problem reported.
For the rest of your opinions, I totally understand how painful those would be to developers.
(I will try my best to bring that amazing improvement for doing design on watch.)
I will make your story to reach Tizen .NET team, so we can make Tizen way better. 
Thanks again for sharing your valuable experience.
I will look forward to update our improvements to you :)

Best Regards,
Jay Cho
