### ISSUE TITLE
Splash screen memory leak?

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.NET#60]
I have followed [this article ](https://samsung.github.io/Tizen.NET/tizen.net/Adding-a-splash-screen-to-your-Tizen-.NET-application/)  to add splash screen on my wearable app using tizen 4.0.
It seems that using splash image causes memory leark and memory usage increases. is it because although splash image disappears but it is not collected by GC and remains in the memory? if it is the case, can we do something about it?

**Comment by rookiejava** [comment]
Thank you for reporting. 

/cc @pjh9216 Could you take a look this issue?

**Comment by rookiejava** [comment]
@EmilAlipiev Can you share more information to find out the cause? This would be helpful.
e.g. which tools and methods you used to measure memory usage, and which binary (target? or emulator?) did you use, and so on.
