### ISSUE TITLE
SendDisappearingEventOnPause / SendAppearingEventOnResume for Tizen

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.NET#62]
I have just created an issue on Xamarin github [here](https://github.com/xamarin/Xamarin.Forms/issues/9844). For a cross issue, it might be helpful here as well.

**Comment by rookiejava** [comment]
I've left comments on Xamarin.Forms issue you opened.

**Comment by EmilAlipiev** [comment]
Thanks I think that we can close this one here
