### ISSUE TITLE
Does Tizen .NET support an API for tracking REM sleep?

### ISSUE THREAD

**Issue by rookiejava** [Samsung/Tizen.NET#63]
> _This question was created from a question from 3rd part developer ([@Keytoll_](https://twitter.com/Keytoll_))_

Need to provide guide how to track REM sleep with Tizen .NET.

**Comment by rookiejava** [comment]
Please refer to [SleepMonitor](https://samsung.github.io/TizenFX/API4/api/Tizen.Sensor.SleepMonitor.html) API

**Comment by Keytoll** [comment]
Unfortunately I could only find three sleep states: sleep, wake and unknown. No rem sleep state publically available to my knowledge.

**Comment by 406411350** [comment]
I have the same problem?
Did you have any source to get the data
