### ISSUE TITLE
VS Code Tizen.NET Extension not working

### ISSUE THREAD

**Issue by ahmednrana** [Samsung/Tizen.NET#66]
Installing / Activating the TIzen.NET extension for marketplace gives the following error.

Cannot activate the 'Tizen .NET' extension because it depends on an unknown 'ms-vscode.csharp' extension .

Looks like Microsoft changed their extension id to `ms-dotnettools.csharp` instead of `ms-vscode.csharp`.

**Comment by JoonghyunCho** [comment]
@sangwook96-lee, @winstone77, Please take a look at this issue.

**Comment by rookiejava** [comment]
@sangwook96-lee, @winstone77 Any updates?

**Comment by aleybe** [comment]
Unfortunately I'm unsure how to resolve this issue, I'll have to download VS instead :/

**Comment by aleybe** [comment]
Alright guys I have found a work around that seems to be working for me. 

Go to one of these depending on your OS. 

    Windows %USERPROFILE%\. vscode\extensions.
    macOS ~/. vscode/extensions.
    Linux ~/. vscode/extensions.

Find the `tizen.vscode-tizen-csharp-1.2.0` extension

Inside that there is a `.vsixmanifest`

Change the `<Property Id="Microsoft.VisualStudio.Code.ExtensionDependencies" Value="ms-vscode.csharp" />` to `ms-dottnettools.csharp`

Now inside the `packages.json` there is also a 

`"extensionDependencies": [
		"ms-vscode.csharp"
	],`

which you will need to change aswell.

**Comment by CalebProvost** [comment]
@aleybe  
Thanks, but you have a typo:  
> Change the `<Property Id="Microsoft.VisualStudio.Code.ExtensionDependencies" Value="ms-vscode.csharp" />` to `ms-dottnettools.csharp`

There's an extra 't'.  Should be `ms-dotnettools.csharp`

**Comment by sep-sabeti** [comment]
Guys it worked !! thank you so much ! it drove me crazy for a day !

**Comment by winstone77** [comment]
This issue was resolved in latest vscode extension for tizen.
