### ISSUE TITLE
CookiePersistentStorage.Text not considered

### ISSUE THREAD

**Issue by hadihashem** [Samsung/Tizen.NET#67]
**Describe the bug**
Error in function CookieManager.SetPersistentStorage: The parameter storage is not considered

**To Reproduce**
1. Use the line code CookieManager.SetPersistentStorage(Program.Current.DirectoryInfo.Data, CookiePersistentStorage.Text);
2. The cookies are stored in SQLite format instead of Text format

**Expected behavior**
The cookies should be stored using the format specified in the storage variable

**Screenshots**

**Environment (please complete the following information):**
 - Common, Mobile, TV, Wearable
 - Tizen.NET 5.0.0.14629

**Additional context**

**Comment by younghajung** [comment]
Chromium does not support text file based cookie storage.
CookiePersistentStorage.Text will be deprecated soon.
Thank you.
