### ISSUE TITLE
How to read cookies saved using CookieManager.SetPersistentStorage()?

### ISSUE THREAD

**Issue by hadihashem** [Samsung/Tizen.NET#68]
Hello

In order to read the cookies saved using CookieManager.SetPersistentStorage, I expected to have the function CookieManager.GetCookies() as per this example:
https://www.javatips.net/api/android.webkit.cookiemanager

However, this function is not available
Is there any other way to read the cookies?

Regards

**Comment by younghajung** [comment]
Unfortunately, it is not provided at the moment.
Tizen.WebView supports functions for simple browsing for now.
But, we plan to support more APIs gradually.
API that gets a cookie will be introduced on the next Tizen version.
