### ISSUE TITLE
Could not find Visual Studio for Mac Extension for Tizen

### ISSUE THREAD

**Issue by Husseinhj** [Samsung/Tizen.NET#70]
I have Visual Studio for Mac v8.5.1 on Catalina mac os v10.15.4 (19E266). Based on your documentation I couldn't find **Visual Studio for Mac Extension for Tizen** in visual studio extension.

**Screenshots**
<img width="400" alt="Visual Studio version" src="https://user-images.githubusercontent.com/27139702/78562426-91502980-782e-11ea-83eb-2333ddd5644f.png">

<img width="300" alt="Visual Studio version" src="https://user-images.githubusercontent.com/27139702/78562143-256dc100-782e-11ea-9e62-a41923214802.png">

<img width="500" alt="Visual Studio for Mac Extension" src="https://user-images.githubusercontent.com/27139702/78561916-bee8a300-782d-11ea-8b29-20ce5e283298.png">

**Comment by Juwols** [comment]
@sangwook96-lee,
Could you check this issue?

**Comment by sangwook96-lee** [comment]
Hi,
Thanks for asking it here.

https://docs.tizen.org/application/vstools-mac/overview
We officially announce it supporting on Mojave 10.14 version. 
This year, we will consider to work it on Catalina version, too 

Thank you very much.!!!

**Comment by Husseinhj** [comment]
Thanks for the pieces of information.

> This year, we will consider to work it on Catalina version, too

Do you have any idea when it will be available on the Catalina version?
For developers it's important to use the latest version of OS, especially in the Apple ecosystem.

**Comment by Husseinhj** [comment]
Any update?

**Comment by striboldt** [comment]
We really need this.

**Comment by vivek-ellur** [comment]
Hi,

Its available in Extension Manager, Can you click refresh button in gallery and check it under IDE Extension tab.

**Comment by striboldt** [comment]
Thanks Vivek, the extension is now available 👍

**Comment by nishtahir** [comment]
Looks like this issue might need to be reopened because the extension is no longer available since the process for releasing extensions has changed https://docs.microsoft.com/en-us/visualstudio/mac/migrate-extensions?view=vsmac-2019
