### ISSUE TITLE
Network service discovery, ssdp not working Samsung Watch with visual studio

### ISSUE THREAD

**Issue by devop06** [Samsung/Tizen.NET#71]
**Describe the bug**
I'm on Visual Studio 2017 for Windows with a Samsung galaxy watch SM R800 to Tizen 4.0.0.4.

i want to use network service discoveries, more precisely ssdp feature to discover a device in my home network. 

I got this error (tizen log): 

04-11 12:17:18.465 | Error | 4595 | 4595 | CAPI_NETWORK_SSDP | ssdp.c: ssdp_initialize(433) > http://tizen.org/feature/network.service_discovery.ssdp feature is disabled

04-11 12:17:18.549 | Error | 4595 | 4595 | Tizen.Network.Nsd | Globals.cs: SsdpInitialize(41) > Failed to initialize Ssdp, Error - NotSupported

API version : Tizen 4.0

i applied these features in my manifest :
- network.service_discovery.ssdp
privileges : 
- privilege/internet

so i don't understand why i get this message.
 
Once compiled and deployed to the device for debugging, in VS I get:

**Frame not in module

The current stack frame was not found in a loaded module. Source cannot be shown for this location.**

App just crashes and shut down debugger process..

thanks for your help, i hope i'm in the right section.

**Comment by TizenHelper** [comment]
Hi,
Thank you for asking.
SSDP feature is not supported on Samsung Galaxy Watch.

```
bool _isSsdpServiceSupported;

Information.TryGetValue<bool>("http://tizen.org/feature/network.service_discovery.ssdp", out _isSsdpServiceSupported);

if (_isSsdpServiceSupported) {
   // You can use SSDP
} else {
   // SSDP feature is not supported on this device.
}
```
@chleun-moon,
Please confirm whether Galaxy Watch supports SSDP or not.
Thank you in advance.

**Comment by TizenHelper** [comment]
It turns out to be a problem that only occurs on some models(including SM-R800) of Galaxy Watch. So we ask the person in charge to fix this issue.
Unfortunately, there's no SW update (Tizen 4.0 MR) plan for this model at this moment.
We'll share it with you if there's any news.
Thanks.

**Comment by devop06** [comment]
Indeed, it's not supported. (_isSsdpServiceSupported  == false)
it's a shame, thank you for your help. 
Yes if can you keep me informed. 
thank you
