### ISSUE TITLE
SQLite : forbidden assembly

### ISSUE THREAD

**Issue by nmadrane** [Samsung/Tizen.NET#72]
**Describe the bug**
Trying to integrate SQLite in my Tizen.NET (TV) application. As soon as I launch the application on my tv set, I get an error message saying that sqlite3 is forbidden.

**To Reproduce**
1. Create an empty Tizen.NET TV application with VS 2019
2. Add the following Nuget Packages
  - sqlite-net-base
  - SQLitePCLRaw.provider.sqlite3.netstandard11
3. Launch the application on a TV
4. You get the error "sqlite3 forbidden assembly"

**Expected behavior**
Application should run without this exception

**Environment (please complete the following information):**
 - Target Product : Samsung Smart TV 2018
 - Tizen Platform Version : Tizen 5.0 TV

**Comment by TizenHelper** [comment]
Hi,
This issue only occurs in Samsung Smart TV products. (SQLite works in Tizen platform emulator and Galaxy Watch devices.)
As mentioned in [tizen forum](https://developer.tizen.org/forums/tizen-.net/forbidden-assembly), we're still waiting for TV product team's answer. Thank you for your patience.

**Comment by TizenHelper** [comment]
Sorry for informing you of this kind of news.
Due to the security policy of Samsung TV products, loading the library provided by TV product using DllImport is not supported.
(In this case, SQLitePCLRaw.provider.sqlite3 dll is trying to load sqlite3 library provided by TV product through DllImport and it's not allowed on Samsung TV products.)
This policy seems to be maintained for the time being.
Thanks.

**Comment by nmadrane** [comment]
Ok thanks for your feedback. I will try to find another solution for a local database in my TV project. Something that is pure CLR.

**Comment by Filliny** [comment]
B..but your Tizen TV project termplates from start gives the same error - 
![viber_image_2020-05-07_09-32-49](https://user-images.githubusercontent.com/25462974/81262075-d17d1480-9045-11ea-906a-fd2feae4404a.jpg)
![Microsoft_Visual_Studio_2020-05-07_09-31-03](https://user-images.githubusercontent.com/25462974/81262108-e063c700-9045-11ea-9088-ed6f80630199.png)

**Comment by Filliny** [comment]
This solves problem ( Like it does now for Tizen Xaml App solution termplate from scratch) : 

![STVXamarinApplication1_-_Microsoft_Visual_Studio_2020-05-07_10-09-18](https://user-images.githubusercontent.com/25462974/81265120-31c28500-904b-11ea-9601-b43cf5d2973e.png)
