### ISSUE TITLE
Tizen TV 5.0 (4.0 & so on) solutions termplate projects fail to run from scratch

### ISSUE THREAD

**Issue by Filliny** [Samsung/Tizen.NET#73]
**Describe the bug**
Solution termplates failed to run without any modifications.  TV reports that : 
_**Fail to Launch your App.
[FAIL ] .Tizen.TV.dll refers a forbidden
assembly directly - Xamarin.Forms.PIatform.Tizen :(**_

**To Reproduce**
1. Create in  Visual Studio empty project from termplate Tizen Samsung TV 5.0 
2. Dont change anything 
3. Build and deploy to TV
4. See error [FAIL ] .Tizen.TV.dll refers a forbidden
assembly directly - Xamarin.Forms.PIatform.Tizen
5. When deploy to emulator u will se no any errors on emu - only fail start to debug from IDE like so when deploy to TV

**Expected behavior**
We expect to project run happily.

**Screenshots**
![Microsoft_Visual_Studio_2020-05-07_09-31-03](https://user-images.githubusercontent.com/25462974/81266302-3720cf00-904d-11ea-9488-b15b7bbc41eb.png)
![viber_image_2020-05-07_09-32-49](https://user-images.githubusercontent.com/25462974/81266339-44d65480-904d-11ea-8c7d-b21f8332a12e.jpg)

**Environment (please complete the following information):**
 - Target Product  Samsung TV 2019  E55Q77RAUXUA
 - Tizen Platform Version [Tizen 5.0]

**Additional context**
Changing Namespace for STVXamarinApplication1.Tizen.TV.cs.  to  "STVXamarinApplication1.Tizen" solves the problem - application run sucesfully
![STVXamarinApplication1_-_Microsoft_Visual_Studio_2020-05-07_10-09-18](https://user-images.githubusercontent.com/25462974/81266276-2d976700-904d-11ea-84fc-5b731db655f0.png)

**Comment by TizenHelper** [comment]
Hi,
Sorry for the inconvenience.
Do you mean that the issue is solved after just modifying as below

```
namespace STVXamarinApplication1.Tizen.TV
->
namespace STVXamarinApplication1.Tizen
```
In my case, the problem was not solved with your solution.

Do you use VS 2019?
I checked that  TV .NET app is running on TV after modifying as below:

1. STVXamarinApplication1.csproj
```
<Project Sdk="Tizen.NET.Sdk/1.0.3">
=>
<Project Sdk="Microsoft.NET.Sdk">
```
 
2. STVXamarinApplication1.Tizen.TV.csproj
```
<Project Sdk="Tizen.NET.Sdk/1.0.3">
=>
<Project Sdk="Tizen.NET.Sdk/1.0.9">
```
Please give it a try.
Regarding the issue, we asked the person in charge of distributing TV app template to check and fix it.
Thanks.

**Comment by Filliny** [comment]
Yes - sorry, I'we cheked and really- i have made your modifications early , prior to renaming of namespace. So after renaming namespace all run fine. And  yes - VS2019.
Thanx for reply - expect for changes!)

**Comment by winstone77** [comment]
It seems that this issue already resolved.
