### ISSUE TITLE
Support .NET Standard 2.1

### ISSUE THREAD

**Issue by VladislavAntonyuk** [Samsung/Tizen.NET#74]
Currently application is build using .NET Standard 2.0, which limit us from using new EntityFramework and so on, which supports .NET Standard 2.1 or higher

**Comment by WonyoungChoi** [comment]
@VladislavAntonyuk  Supports netstandard2.1 from tizen60 tfm. And the tizen60 tfm is available in Tizen 5.5 M2 platform. (https://www.tizen.org/blogs/tsg/2019/tizen-5.5-public-m2-release)
