### ISSUE TITLE
Tpk includes excluded files in VS 2019

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.NET#76]
**Describe the bug**
I have just unzipped tpk file and under res folder there were images are excluded from my VS 2019 solution but they are bundled into tpk file.
 
**Expected behavior**
They should not be included into tpk
 
**Environment (please complete the following information):**
 - Galaxy Watch application
 - Tizen 4.0

**Comment by TizenHelper** [comment]
@sangwook96-lee,
Could you check this issue?
Thank you in advance.

**Comment by sangwook96** [comment]
@EmilAlipiev 
Hi,
Thanks for asking it here.
I have one query to you.
1. How did you exclude the images from app ?
2. What did you use Visual Studio Tools for Tizen version ? The curren version is 3.1.0.0.
Kindly let me know.
Thank you and regards.

**Comment by dkson95** [comment]
Closing invalid issue!
