### ISSUE TITLE
Bluetooth Support in WebView

### ISSUE THREAD

**Issue by zacharee** [Samsung/Tizen.NET#77]
**Is your feature request related to a problem? Please describe.**
Currently, the wearable dotnet WebView only supports connections over WiFi/LTE. With only Bluetooth on, DNS can't resolve.

**Describe the solution you'd like**
The WebView should support loading pages over Bluetooth. Samsung Internet can load pages like that, so it must be technically possible.

**Describe alternatives you've considered**
Forcing WiFi to turn on is a potential alternative, but not a desirable workaround.

**Comment by younghajung** [comment]
Tizen.WebView is supported within the scope supported by the native webview (ewk view).
Unfortunately, both native and Tizen.WebView are not planning to support Bluetooth connection.

**Comment by zacharee** [comment]
This seems like a pretty basic limitation. How can I request it as a feature for the native API?
