### ISSUE TITLE
Gear S3 with Tizen 4.0.0.7 missing SAP library, all companion apps crash.

### ISSUE THREAD

**Issue by matthewkrueger** [Samsung/Tizen.NET#79]
**Describe the bug**
I'm just about to release version 1.0 of a new Tizen companion app for a very popular Android app. Our users have been anticipating this for years. I had a beta tester try out the app and it works fine on his Galaxy Watch. It also works fine on the Watch Active 2 and Galaxy Watch 3 that I bought for development.

On his Gear S3, the Tizen app will not even open. I was able to get him to pull logs, and we're seeing this:

`Info / DOTNET_LAUNCHER ( 5942 : 5946 ) : System.TypeInitializationException: The type initializer for 'MyCoolTizenApp.sync.PhoneSync' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Samsung.Sap, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

**To Reproduce**
1. Get a Gear S3 with Tizen 4.0.0.7
2. Run any Tizen companion app that relies on the SAP library

**Expected behavior**
The app should open and not crash

**Screenshots**
Screenshots won't really help here - the app won't open.

**Environment (please complete the following information):**
 - Target Product Galaxy Watch
 - Tizen Platform Version Tizen 4.0 and newer

**Additional context**
The app was built with Tizen .NET. As I stated before, it works fine on all other Tizen watches. I read somewhere that Tizen 4.0.0.7 for the Gear S3 is completely broken and the SAP library was actually REMOVED from the Operating system. Is this true? Can you provide more information to corroborate this?

Here's the link where I first saw that Tizen 4.0.0.7 is completely broken on the Gear S3: https://eu.community.samsung.com/t5/wearables/recent-s3-frontier-firmware-update-broke-third-party-app/td-p/1779362

Note: My beta tester used some tools to downgrade his OS version to 4.0.0.2 and our app works perfectly again, so the link above seems like a valid issue. Not sure how it's possible that such a core system library has been removed from a very popular Tizen watch.

Thanks in advance for your help!

**Comment by Ornolfr** [comment]
@TizenHelper I've got the same exact issue with my app that is written in Native C/C++. Please advise on how this can be fixed.
