### ISSUE TITLE
Using third-party libraries on TizenTV .NET application

### ISSUE THREAD

**Issue by vitalii-smal** [Samsung/Tizen.NET#81]
Hi, 

I am new to developing Tizen .NET applications, in my case for Tizen TV. 

I tried to port my Xamarin Forms application for TizenTV, but I got problems with my NuGet packages, when I tried to launch it on the physical device with Tizen OS. 

It shows me next error: 
`[FAIL] SQLitePCLRaw.provider.sqlite3.dll refers a forbidden assembly directly - sqlite3 :( `

Does anybody know either it is possible to fix, or I must exclude this NuGet package from my app in order to publish application Samsung Apps TV Seller Office? 

Regards,
Vitalii

**Comment by EmilAlipiev** [comment]
Can you try to initialize sqlite like below?

```
class Program : FormsApplication
    {
        protected override void OnCreate()
        {
            base.OnCreate();

            SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_sqlite3());

            LoadApplication(new App());
        }
```

see the answer below also https://stackoverflow.com/questions/55464505/how-can-i-use-sqlite-in-tizen-net-c

**Comment by rookiejava** [comment]
Unfortunately, as guided in the FAQ [here](https://developer.samsung.com/tizen/Smart-TV/FAQ/FAQ.html), existing TV product doesn't allow to import external dll (through  `DllImport`) for security reasons. 

However, if I know correctly, this restriction will be removed from the 2021 TV models with Tizen 6.5.
