### ISSUE TITLE
Updating Tizen Studio by overriding Sdk data

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.NET#83]
I install first Tizen Studio to get the latest SDK and other tools intead of directly using Visual Studio. Because somehow 
using directly VS causes some issues on emulators. Here is the problem. Tizen Studio doesnt have a proper update option and i need to go to website to download the latest version and kid of reinstall it but installation process doesnt allow me to override the exisiting Tizen Studio Data and Sdk and ask me to choose a new path. Can we get that properly updating instead of installing on a new location every time?

**Comment by dkson95** [comment]
> Can we get that properly updating instead of installing on a new location every time?

@EmilAlipiev could you check the way of update by https://developer.tizen.org/development/tizen-studio/download/installing-tizen-studio/updating-tizen-studio ?
