### ISSUE TITLE
VS 2019 Tizen template shows subfolders on adding new project to existing XF solution

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.NET#84]
When I want to add a Tizen project on my existing XF project. It displays solution folders like below, instead of existing project.
You can simply reproduce it by
- create new XF solution
- add each Project to solution folders
- add new Tizen project to the Sln
- 
![image](https://user-images.githubusercontent.com/10422347/102945228-75281180-44bd-11eb-8af4-40fdaf8f482a.png)

**Comment by dkson95** [comment]
@EmilAlipiev thank you for the report, but, could you describe your issue more in detail with the latest vsix and example if possible, please ?

**Comment by dkson95** [comment]
closing invalid issue.
