### ISSUE TITLE
Certificate Manager Create new certificate missing "Device Type" step

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.NET#85]
I updated to tizen studio 4 and when i try to create a new certificate, it starts directly with profile name.
Before and according to the documentation also, there was device type step.
so my question is, was that removed and now all device types uses same certificate?
i dont need to create for watch and tv different one?
If that is the case, i created a new certificate which doesnt work on tv.

![image](https://user-images.githubusercontent.com/10422347/102949857-942ca080-44c9-11eb-8f82-4c816df40613.png)

https://samsung.github.io/Tizen.CircularUI/guide/CreatingCertificates.html

**Comment by rexopl** [comment]
Yeah there is other GUI for cert manager now, how to add DUID now?

**Comment by rexopl** [comment]
I was looking for the same, and found it. There is Samsung Certificate Extension to install in package manager in Extension SDK tab.

**Comment by dkson95** [comment]
> There is Samsung Certificate Extension to install in package manager in Extension SDK tab.
> https://developer.samsung.com/galaxy-watch-develop/getting-certificates/install.html
> 
> Anyway still can create proper cert.

Nice catch! @EmilAlipiev Tizen SDK provides `Samsung` cert for store upload or, `Tizen` cert. for local use

https://docs.tizen.org/application/dotnet/tutorials/certificates/creating-certificates/
> Select Samsung as the certificate profile to generate certificates to develop and install an application to the Samsung devices. To upload the application to the store, you must select the certificate profile as Samsung. However, if you want to use the emulator and do not want to upload the application to the store, select Tizen to create certificate locally.
